Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  #master_config.vm.provision :shell, :inline => $rhel_centos_puppet_master_script  

  ####################
  ####################
  config.vm.box = "centos-6.4-amd64"
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  
 #a puppet master
 config.vm.define "sshmaster".to_sym do |sshmaster_config|
  sshmaster_config.vm.box = "ubuntu-13.04-server-amd64"
	sshmaster_config.vm.hostname = "sshmaster.local"
	sshmaster_config.hostmanager.enabled = true
	#giving it 'puppet' as an alias so that the agents can connect to it with their default settings
	sshmaster_config.hostmanager.aliases = %w(puppet sshmaster)
	sshmaster_config.vm.network :private_network, ip: "10.0.1.60"
	#set some machine-specific options	
	sshmaster_config.vm.provider "virtualbox" do |v|
    #change the amount of RAM 
    v.customize ["modifyvm", :id, "--memory", "1024"]
  end
  end

 #an ssh client
 config.vm.define "ssh1".to_sym do |ssh1_config|
  ssh1_config.vm.box = "ubuntu-13.04-server-amd64"
	ssh1_config.vm.hostname = "ssh1.local"
	ssh1_config.hostmanager.enabled = true
	ssh1_config.vm.network :private_network, ip: "10.0.1.61"
	#set some machine-specific options	
	ssh1_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end

 #another ssh client
 config.vm.define "ssh2".to_sym do |ssh2_config|
  ssh2_config.vm.box = "centos-6.4-amd64"
	ssh2_config.vm.hostname = "ssh2.local"
	ssh2_config.hostmanager.enabled = true
	ssh2_config.vm.network :private_network, ip: "10.0.1.62"
	#set some machine-specific options	
	ssh2_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end

 #another ssh client
 config.vm.define "ssh3".to_sym do |ssh3_config|
  ssh3_config.vm.box = "debian-7.1-amd64"
	ssh3_config.vm.hostname = "ssh3.local"
	ssh3_config.hostmanager.enabled = true
	ssh3_config.vm.network :private_network, ip: "10.0.1.63"
	#set some machine-specific options	
	ssh3_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
end