Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #Puppet master
  config.vm.define "influxdbmaster".to_sym do |influxdbmaster_config|
    influxdbmaster_config.vm.box = "ubuntu-13.10-server-amd64"
    influxdbmaster_config.vm.hostname = "influxdbmaster.local"
    influxdbmaster_config.hostmanager.aliases = %w(master puppet master.local puppetboard.influxdbmaster.local)
    influxdbmaster_config.vm.network :private_network, ip: "10.0.1.170"
    #set some machine-specific options	
    influxdbmaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    influxdbmaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    influxdbmaster_config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    influxdbmaster_config.vm.synced_folder "hieradata", "/etc/puppet/environments/production/hieradata", :nfs => true
    #Puppet master provisioning script
    influxdbmaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"
  end

  #A machine running InfluxDB
  config.vm.define "influxdb1".to_sym do |influxdb1_config|
    influxdb1_config.vm.box = "ubuntu-13.10-server-amd64"
    influxdb1_config.vm.hostname = "influxdb1.local"
    influxdb1_config.vm.network :private_network, ip: "10.0.1.171"
    #set some machine-specific options	
    influxdb1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  influxdb1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #A machine running InfluxDB
  config.vm.define "influxdb2".to_sym do |influxdb2_config|
    influxdb2_config.vm.box = "ubuntu-13.10-server-amd64"
    influxdb2_config.vm.hostname = "influxdb2.local"
    influxdb2_config.vm.network :private_network, ip: "10.0.1.172"
    #set some machine-specific options	
    influxdb2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    influxdb2_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #A machine running InfluxDB
  config.vm.define "influxdb3".to_sym do |influxdb3_config|
    influxdb3_config.vm.box = "centos-6.5-amd64"
    influxdb3_config.vm.hostname = "influxdb3.local"
    influxdb3_config.vm.network :private_network, ip: "10.0.1.173"
    #set some machine-specific options	
    influxdb3_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  influxdb3_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #A machine running InfluxDB
  config.vm.define "influxdb4".to_sym do |influxdb4_config|
    influxdb4_config.vm.box = "centos-6.5-amd64"
    influxdb4_config.vm.hostname = "influxdb4.local"
    influxdb4_config.vm.network :private_network, ip: "10.0.1.174"
    #set some machine-specific options	
    influxdb4_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  influxdb4_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

end
