Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #Puppet master and fail2ban machine
  config.vm.define "influxdbmaster".to_sym do |influxdbmaster_config|
    influxdbmaster_config.vm.box = "ubuntu-13.10-server-amd64"
    influxdbmaster_config.vm.hostname = "influxdbmaster.local"
    influxdbmaster_config.hostmanager.aliases = %w(master puppet master.local puppetboard.influxdbmaster.local)
    influxdbmaster_config.vm.network :private_network, ip: "10.0.1.70"
    #set some machine-specific options	
    influxdbmaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    influxdbmaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules", :nfs => true
    influxdbmaster_config.vm.synced_folder "manifests/", "/etc/puppet/manifests", :nfs => true
    influxdbmaster_config.vm.synced_folder "hieradata", "/etc/puppet/hieradata", :nfs => true
    #Puppet master provisioning script
    influxdbmaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master.sh"
  end
end
