Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #Puppet master and denyhosts server
  config.vm.define "dnspuppetmaster".to_sym do |master_config|
    master_config.vm.box = "ubuntu-14.04-server-amd64"
    master_config.vm.hostname = "dnspuppetmaster.local"
    master_config.hostmanager.aliases = %w(master puppet master.local puppetboard.dnspuppetmaster.local)
    master_config.vm.network :private_network, ip: "10.0.1.70"
    #set some machine-specific options	
    master_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    config.vm.synced_folder "hieradata", "/etc/puppet/environments/production/hieradata", :nfs => true
    config.vm.synced_folder "files/", "/etc/puppet/files", :nfs => true
    #Puppet master provisioning script
    master_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"
  end

  #An Ubuntu BIND DNS master server
  config.vm.define "dnsmaster1".to_sym do |dnsmaster1_config|
    dnsmaster1_config.vm.box = "ubuntu-14.04-server-amd64"
    dnsmaster1_config.vm.hostname = "dnsmaster1.local"
    dnsmaster1_config.vm.network :private_network, ip: "10.0.1.71"
    #set some machine-specific options	
    dnsmaster1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
	  dnsmaster1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #A CentOS BIND DNS master server
  config.vm.define "dnsmaster2".to_sym do |dnsmaster2_config|
    dnsmaster2_config.vm.box = "centos-7.0-amd64"
    dnsmaster2_config.vm.hostname = "dnsmaster2.local"
    dnsmaster2_config.vm.network :private_network, ip: "10.0.1.72"
    #set some machine-specific options	
    dnsmaster2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
	  dnsmaster2_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #An Ubuntu BIND DNS slave
  config.vm.define "dnsslave1".to_sym do |dnsslave1_config|
    dnsslave1_config.vm.box = "ubuntu-14.04-server-amd64"
    dnsslave1_config.vm.hostname = "dnsslave1.local"
    dnsslave1_config.vm.network :private_network, ip: "10.0.1.73"
    #set some machine-specific options	
    dnsslave1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
	  dnsslave1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end
  
  #A CentOS BIND DNS slave
  config.vm.define "dnsslave2".to_sym do |dnsslave2_config|
    dnsslave2_config.vm.box = "centos-7.0-amd64"
    dnsslave2_config.vm.hostname = "dnsslave2.local"
    dnsslave2_config.vm.network :private_network, ip: "10.0.1.74"
    #set some machine-specific options	
    dnsslave2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
	  dnsslave2_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #An Ubuntu BIND DNS client
  config.vm.define "dnsclient1".to_sym do |dnsclient1_config|
    dnsclient1_config.vm.box = "ubuntu-14.04-server-amd64"
    dnsclient1_config.vm.hostname = "dnsclient1.local"
    dnsclient1_config.vm.network :private_network, ip: "10.0.1.75"
    #set some machine-specific options	
    dnsclient1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
	  dnsclient1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end
  
  #A CentOS BIND DNS client
  config.vm.define "dnsclient2".to_sym do |dnsclient2_config|
    dnsclient2_config.vm.box = "centos-7.0-amd64"
    dnsclient2_config.vm.hostname = "dnsclient2.local"
    dnsclient2_config.vm.network :private_network, ip: "10.0.1.76"
    #set some machine-specific options	
    dnsclient2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
	  dnsclient2_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #A mail server VM for sending emails about DNS stuff
  config.vm.define "dnsmail".to_sym do |dnsmail_config|
    dnsmail_config.vm.box = "ubuntu-14.04-server-amd64"
    dnsmail_config.vm.hostname = "dnsmail.local"
    dnsmail_config.vm.network :private_network, ip: "10.0.1.77"
    #set some machine-specific options	
    dnsmail_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
	  dnsmail_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #A Riemann/InfluxDB/Grafana VM for gathering and graphing DNS metrics
  config.vm.define "dnsmetrics".to_sym do |dnsmetrics_config|
    dnsmetrics_config.vm.box = "ubuntu-14.04-server-amd64"
    dnsmetrics_config.vm.hostname = "dnsmetrics.local"
    dnsmetrics_config.hostmanager.aliases = %w(grafana.dnsmetrics.local)
    dnsmetrics_config.vm.network :private_network, ip: "10.0.1.78"
    #set some machine-specific options	
    dnsmetrics_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #Puppet agent provisioning script
	  dnsmetrics_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #An Elasticsearch/Logstash/Kibana VM 
  config.vm.define "dnslogging".to_sym do |dnslogging_config|
    dnslogging_config.vm.box = "ubuntu-14.04-server-amd64"
    dnslogging_config.vm.hostname = "dnslogging.local"
    dnslogging_config.vm.network :private_network, ip: "10.0.1.79"
    #set some machine-specific options	
    dnslogging_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #Puppet agent provisioning script
	  dnslogging_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #An Icinga 2 server for monitoring DNS
  config.vm.define "dnsmonitoring".to_sym do |dnsmonitoring_config|
    dnsmonitoring_config.vm.box = "ubuntu-14.04-server-amd64"
    dnsmonitoring_config.vm.hostname = "dnsmonitoring.local"
    dnsmonitoring_config.vm.network :private_network, ip: "10.0.1.80"
    #set some machine-specific options	
    dnsmonitoring_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    dnsmonitoring_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

end
