Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #Puppet master and denyhosts server
  config.vm.define "dnspuppetmaster".to_sym do |dnspuppetmaster_config|
    dnspuppetmaster_config.vm.box = "ubuntu-14.04-server-amd64"
    dnspuppetmaster_config.vm.hostname = "dnspuppetmaster.local"
    dnspuppetmaster_config.hostmanager.aliases = %w(puppet dnspuppetmaster.local puppetexplorer.dnspuppetmaster.local puppetboard.dnspuppetmaster.local)
    dnspuppetmaster_config.vm.network :private_network, ip: "10.0.1.70"
    #set some machine-specific options	
    dnspuppetmaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    dnspuppetmaster_config.vm.synced_folder "production/", "/etc/puppet/environments/production", :nfs => true
    dnspuppetmaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    dnspuppetmaster_config.vm.synced_folder "hieradata/", "/etc/puppet/environments/production/hieradata", :nfs => true
    dnspuppetmaster_config.vm.synced_folder "files/", "/etc/puppet/files", :nfs => true
    #Puppet master provisioning script
    dnspuppetmaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"
  end

  #An Ubuntu BIND DNS master server
  config.vm.define "dnsmaster1".to_sym do |dnsmaster1_config|
    dnsmaster1_config.vm.box = "centos-7.0-amd64"
    dnsmaster1_config.vm.hostname = "dnsmaster1.local"
    dnsmaster1_config.vm.network :private_network, ip: "10.0.1.71"
    #set some machine-specific options	
    dnsmaster1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
	  dnsmaster1_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #A CentOS BIND DNS master server
  config.vm.define "dnsmaster2".to_sym do |dnsmaster2_config|
    dnsmaster2_config.vm.box = "centos-7.0-amd64"
    dnsmaster2_config.vm.hostname = "dnsmaster2.local"
    dnsmaster2_config.vm.network :private_network, ip: "10.0.1.72"
    #set some machine-specific options	
    dnsmaster2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
	  dnsmaster2_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #An Ubuntu BIND DNS slave
  config.vm.define "dnsslave1".to_sym do |dnsslave1_config|
    dnsslave1_config.vm.box = "centos-7.0-amd64"
    dnsslave1_config.vm.hostname = "dnsslave1.local"
    dnsslave1_config.vm.network :private_network, ip: "10.0.1.73"
    #set some machine-specific options	
    dnsslave1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
	  dnsslave1_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end
  
  #A CentOS BIND DNS slave
  config.vm.define "dnsslave2".to_sym do |dnsslave2_config|
    dnsslave2_config.vm.box = "centos-7.0-amd64"
    dnsslave2_config.vm.hostname = "dnsslave2.local"
    dnsslave2_config.vm.network :private_network, ip: "10.0.1.74"
    #set some machine-specific options	
    dnsslave2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
	  dnsslave2_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #An Ubuntu BIND DNS client
  config.vm.define "dnsclient1".to_sym do |dnsclient1_config|
    dnsclient1_config.vm.box = "centos-7.0-amd64"
    dnsclient1_config.vm.hostname = "dnsclient1.local"
    dnsclient1_config.vm.network :private_network, ip: "10.0.1.75"
    #set some machine-specific options	
    dnsclient1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
	  dnsclient1_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end
  
  #A CentOS BIND DNS client
  config.vm.define "dnsclient2".to_sym do |dnsclient2_config|
    dnsclient2_config.vm.box = "centos-7.0-amd64"
    dnsclient2_config.vm.hostname = "dnsclient2.local"
    dnsclient2_config.vm.network :private_network, ip: "10.0.1.76"
    #set some machine-specific options	
    dnsclient2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
	  dnsclient2_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #An Elasticsearch/Logstash/Kibana and Riemann/InfluxDB/Grafana and Icinga 2 monitoring VM;
  #also has a mail server for sending email alerts
  config.vm.define "dnsmonitoring".to_sym do |dnsmonitoring_config|
    dnsmonitoring_config.vm.box = "ubuntu-14.04-server-amd64"
    dnsmonitoring_config.vm.hostname = "dnsmonitoring.local"
    dnsmonitoring_config.hostmanager.aliases = %w(grafana.dnsmonitoring.local kibana.dnsmonitoring.local)
    dnsmonitoring_config.vm.network :private_network, ip: "10.0.1.80"
    #set some machine-specific options	
    dnsmonitoring_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #Puppet agent provisioning script
    dnsmonitoring_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #A mail relay server running Postfix:
  config.vm.define "dnsmailrelay".to_sym do |dnsmailrelay_config|
    dnsmailrelay_config.vm.box = "ubuntu-14.04-server-amd64"
    dnsmailrelay_config.vm.hostname = "dnsmailrelay.local"
    dnsmailrelay_config.hostmanager.aliases = %w(dnsmailrelay.local)
    dnsmailrelay_config.vm.network :private_network, ip: "10.0.1.81"
    #set some machine-specific options	
    dnsmailrelay_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    dnsmailrelay_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #A mail server with Dovecot for IMAP
  config.vm.define "dnsusermail".to_sym do |dnsusermail_config|
    dnsusermail_config.vm.box = "ubuntu-14.04-server-amd64"
    dnsusermail_config.vm.hostname = "dnsusermail.local"
    dnsusermail_config.hostmanager.aliases = %w(dnsusermail.local)
    dnsusermail_config.vm.network :private_network, ip: "10.0.1.82"
    #set some machine-specific options	
    dnsusermail_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    dnsusermail_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

end
