Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing for Puppet modules and manifests
    #config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules" #:nfs => true
    #config.vm.synced_folder "manifests/", "/etc/puppet/manifests" #:nfs => true
    #config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/hieradata", "/etc/puppet/hieradata" #:nfs => true
    
    #Puppet provisioning scripts
    #phabricator_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master_script.sh"
    #phabricator_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1310_puppet_agent_script.sh"

  ####################
  ####################

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #A git server
  config.vm.define "git".to_sym do |git_config|
    git_config.vm.box = "ubuntu-13.10-server-amd64"
    git_config.vm.hostname = "git.local"
    git_config.hostmanager.enabled = true
    git_config.hostmanager.aliases = %w(git code.git.local)
    git_config.vm.network :private_network, ip: "10.0.1.78"
    #set some machine-specific options	
    git_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end  

  #Another git server
  config.vm.define "git2".to_sym do |git2_config|
    git2_config.vm.box = "ubuntu-13.10-server-amd64"
    git2_config.vm.hostname = "git2.local"
    git2_config.hostmanager.enabled = true
    git2_config.hostmanager.aliases = %w(git2)
    git2_config.vm.network :private_network, ip: "10.0.1.79"
    #set some machine-specific options	
    git2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
end