Vagrant.configure("2") do |config|
# All Vagrant configuration is done here. The most common configuration
# options are documented and commented below. For a complete reference,
# please see the online documentation at vagrantup.com.

####################
# Snippets to use
####################

#NFS folder sharing
#config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

####################
####################
config.vm.box = "ubuntu-13.04-server-amd64"
config.hostmanager.enabled = true
config.hostmanager.ignore_private_ip = false

    #ganglia web server
    config.vm.define "ambariweb".to_sym do |ambariweb_config|
        ambariweb_config.vm.box = "ubuntu-13.04-server-amd64"
        ambariweb_config.vm.hostname = "ambariweb.local"
        ambariweb_config.hostmanager.enabled = true
        ambariweb_config.vm.network :private_network, ip: "10.0.1.59"
        #set some machine-specific options	
        ambariweb_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
end