Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #A Shibboleth SSO server
  config.vm.define "shibbolethserver".to_sym do |shibbolethserver_config|
    shibbolethserver_config.vm.box = "ubuntu-13.04-server-amd64"
    shibbolethserver_config.vm.hostname = "shibbolethserver.local"
    shibbolethserver_config.hostmanager.enabled = true
    shibbolethserver_config.vm.network :private_network, ip: "10.0.1.191"
    #set some machine-specific options	
    shibbolethserver_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end

  #A Shibboleth SSO client
  config.vm.define "shibbolethclient".to_sym do |shibbolethclient_config|
    shibbolethclient_config.vm.box = "ubuntu-13.04-server-amd64"
    shibbolethclient_config.vm.hostname = "shibbolethclient.local"
    shibbolethclient_config.hostmanager.enabled = true
    shibbolethclient_config.vm.network :private_network, ip: "10.0.1.192"
    #set some machine-specific options	
    shibbolethclient_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
end