Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #Puppet master
  config.vm.define "riemannmaster".to_sym do |riemannmaster_config|
    riemannmaster_config.vm.box = "ubuntu-13.10-server-amd64"
    riemannmaster_config.vm.hostname = "riemannmaster.local"
    riemannmaster_config.hostmanager.aliases = %w(master puppet master.local puppetboard.riemannmaster.local)
    riemannmaster_config.vm.network :private_network, ip: "10.0.1.190"
    #set some machine-specific options	
    riemannmaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    riemannmaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules", :nfs => true
    riemannmaster_config.vm.synced_folder "manifests/", "/etc/puppet/manifests", :nfs => true
    riemannmaster_config.vm.synced_folder "hieradata", "/etc/puppet/hieradata", :nfs => true
    #Puppet master provisioning script
    riemannmaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master.sh"
  end

  #A machine running Riemann
  config.vm.define "riemann1".to_sym do |riemann1_config|
    riemann1_config.vm.box = "ubuntu-13.10-server-amd64"
    riemann1_config.vm.hostname = "riemann1.local"
    riemann1_config.vm.network :private_network, ip: "10.0.1.191"
    #set some machine-specific options	
    riemann1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  riemann1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end

  #A machine running Riemann
  config.vm.define "riemann2".to_sym do |riemann2_config|
    riemann2_config.vm.box = "centos-6.5-amd64"
    riemann2_config.vm.hostname = "riemann2.local"
    riemann2_config.vm.network :private_network, ip: "10.0.1.192"
    #set some machine-specific options	
    riemann2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    riemann2_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

end
