Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #Puppet master and fail2ban machine
  config.vm.define "grafanamaster".to_sym do |grafanamaster_config|
    grafanamaster_config.vm.box = "ubuntu-13.10-server-amd64"
    grafanamaster_config.vm.hostname = "grafanamaster.local"
    grafanamaster_config.hostmanager.aliases = %w(master puppet master.local puppetboard.grafanamaster.local)
    grafanamaster_config.vm.network :private_network, ip: "10.0.1.70"
    #set some machine-specific options	
    grafanamaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    grafanamaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    grafanamaster_config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    grafanamaster_config.vm.synced_folder "hieradata", "/etc/puppet/environments/production/hieradata", :nfs => true
    #Puppet master provisioning script
    grafanamaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"
  end

  #A machine running Grafana
  config.vm.define "grafana1".to_sym do |grafana1_config|
    grafana1_config.vm.box = "ubuntu-13.10-server-amd64"
    grafana1_config.vm.hostname = "grafana1.local"
    grafana1_config.vm.network :private_network, ip: "10.0.1.71"
    #set some machine-specific options	
    grafana1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  grafana1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #A machine running Grafana
  config.vm.define "grafana2".to_sym do |grafana2_config|
    grafana2_config.vm.box = "centos-6.5-amd64"
    grafana2_config.vm.hostname = "grafana2.local"
    grafana2_config.vm.network :private_network, ip: "10.0.1.72"
    #set some machine-specific options	
    grafana2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  grafana2_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end
end
