Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules"
  config.vm.synced_folder "manifests/", "/etc/puppet/manifests"
  config.vm.synced_folder "hieradata/", "/etc/puppet/environments/production/hieradata"

  ####################
  ####################
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #redis instance
  config.vm.define "redis1".to_sym do |redis1_config|
    redis1_config.vm.box = "ubuntu-13.10-server-amd64"
    redis1_config.vm.hostname = "redis1.local"
    redis1_config.hostmanager.enabled = true
    redis1_config.hostmanager.aliases = %w(redis1.local puppet puppet.local)
    redis1_config.vm.network :private_network, ip: "10.0.1.91"
    #set some machine-specific options	
    redis1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    redis1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"
  end

  #redis instance
  config.vm.define "redis2".to_sym do |redis2_config|
    redis2_config.vm.box = "ubuntu-13.10-server-amd64"
    redis2_config.vm.hostname = "redis2.local"
    redis2_config.hostmanager.enabled = true
    redis2_config.hostmanager.aliases = %w(redis2.local)
    redis2_config.vm.network :private_network, ip: "10.0.1.92"
    #set some machine-specific options	
    redis2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    redis2_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #redis instance
  config.vm.define "redis3".to_sym do |redis3_config|
    redis3_config.vm.box = "ubuntu-13.10-server-amd64"
    redis3_config.vm.hostname = "redis3.local"
    redis3_config.hostmanager.enabled = true
    redis3_config.hostmanager.aliases = %w(redis3.local)
    redis3_config.vm.network :private_network, ip: "10.0.1.93"
    #set some machine-specific options	
    redis3_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    redis3_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #redis instance
  config.vm.define "redis4".to_sym do |redis4_config|
    redis4_config.vm.box = "ubuntu-13.10-server-amd64"
    redis4_config.vm.hostname = "redis4.local"
    redis4_config.hostmanager.enabled = true
    redis4_config.hostmanager.aliases = %w(redis4.local)
    redis4_config.vm.network :private_network, ip: "10.0.1.94"
    #set some machine-specific options	
    redis4_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    redis4_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end
end
