Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing for Puppet modules and manifests
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #Puppet master and PuppetDB server
  config.vm.define "icingamaster".to_sym do |icingamaster_config|
    icingamaster_config.vm.box = "ubuntu-13.10-server-amd64"
    icingamaster_config.vm.hostname = "icingamaster.local"
    icingamaster_config.hostmanager.enabled = true
    icingamaster_config.hostmanager.aliases = %w(puppetboard.icingamaster.local icingamaster puppet master)
    icingamaster_config.vm.network :private_network, ip: "10.0.1.78"
    #set some machine-specific options	
    icingamaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/hieradata", "/etc/puppet/environments/production/hieradata", :nfs => true
    #Puppet icingamaster provisioning script
    icingamaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master.sh"
  end  

  #ubuntuicinga server
  config.vm.define "ubuntuicinga".to_sym do |ubuntuicinga_config|
    ubuntuicinga_config.vm.box = "ubuntu-13.10-server-amd64"
    ubuntuicinga_config.vm.hostname = "ubuntuicinga.local"
    ubuntuicinga_config.hostmanager.enabled = true
    ubuntuicinga_config.hostmanager.aliases = %w(ubuntuicinga)
    ubuntuicinga_config.vm.network :private_network, ip: "10.0.1.79"
    #set some machine-specific options	
    ubuntuicinga_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    ubuntuicinga_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end

  #centosicinga server
  config.vm.define "centosicinga".to_sym do |centosicinga_config|
    centosicinga_config.vm.box = "centos-6.5-amd64"
    centosicinga_config.vm.hostname = "centosicinga.local"
    centosicinga_config.hostmanager.enabled = true
    centosicinga_config.hostmanager.aliases = %w(centosicinga)
    centosicinga_config.vm.network :private_network, ip: "10.0.1.80"
    #set some machine-specific options	
    centosicinga_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    centosicinga_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #an icingaserver client
  config.vm.define "icingaclient1".to_sym do |icingaclient1_config|
    icingaclient1_config.vm.box = "ubuntu-13.10-server-amd64"
    icingaclient1_config.vm.hostname = "icingaclient1.local"
    icingaclient1_config.hostmanager.enabled = true
    icingaclient1_config.vm.network :private_network, ip: "10.0.1.81"
    #set some machine-specific options	
    icingaclient1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    icingaclient1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end

  #an icingaserver client
  config.vm.define "icingaclient2".to_sym do |icingaclient2_config|
    icingaclient2_config.vm.box = "centos-6.5-amd64"
    icingaclient2_config.vm.hostname = "icingaclient2.local"
    icingaclient2_config.hostmanager.enabled = true
    icingaclient2_config.vm.network :private_network, ip: "10.0.1.82"
    icingaclient2_config.vm.provider "virtualbox" do |v| 	
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    icingaclient2_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #an icingaserver client
  config.vm.define "icingaclient3".to_sym do |icingaclient3_config|
    icingaclient3_config.vm.box = "ubuntu-13.10-server-amd64"
    icingaclient3_config.vm.hostname = "icingaclient3.local"
    icingaclient3_config.hostmanager.enabled = true
    icingaclient3_config.vm.network :private_network, ip: "10.0.1.83"
    #set some machine-specific options	
    icingaclient3_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    icingaclient3_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end

  #an icingaserver client
  config.vm.define "icingaclient4".to_sym do |icingaclient4_config|
    icingaclient4_config.vm.box = "centos-6.5-amd64"
    icingaclient4_config.vm.hostname = "icingaclient4.local"
    icingaclient4_config.hostmanager.enabled = true
    icingaclient4_config.vm.network :private_network, ip: "10.0.1.84"
    icingaclient4_config.vm.provider "virtualbox" do |v| 	
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    icingaclient4_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end
end
