Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #ganglia web server
  config.vm.define "ubuntugradle".to_sym do |ubuntugradle_config|
    ubuntugradle_config.vm.box = "ubuntu-13.10-server-amd64"
    ubuntugradle_config.vm.hostname = "ubuntugradle.local"
    ubuntugradle_config.hostmanager.enabled = true
    ubuntugradle_config.hostmanager.aliases = %w(ubuntugradle.local)
    ubuntugradle_config.vm.network :private_network, ip: "10.0.1.52"
    #set some machine-specific options	
    ubuntugradle_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  #CentOS Gradle VM
  config.vm.define "centosgradle".to_sym do |centosgradle_config|
    centosgradle_config.vm.box = "centos-6.4-amd64"
    centosgradle_config.vm.hostname = "centosgradle.local"
    centosgradle_config.hostmanager.enabled = true
    centosgradle_config.vm.network :private_network, ip: "10.0.1.53"
    #set some machine-specific options	
    centosgradle_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
end
