Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################
  config.vm.box = "ubuntu-14.04-server-amd64"
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true

  #Password pusher server
  config.vm.define "pwpusher".to_sym do |pwpusher_config|
    pwpusher_config.vm.box = "ubuntu-14.04-server-amd64"
    pwpusher_config.vm.hostname = "pwpusher.local"
    pwpusher_config.hostmanager.enabled = true
    pwpusher_config.vm.network :private_network, ip: "10.0.1.20"
    #set some machine-specific options	
    pwpusher_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
end
