Vagrant.configure("2") do |config|
# All Vagrant configuration is done here. The most common configuration
# options are documented and commented below. For a complete reference,
# please see the online documentation at vagrantup.com.

####################
# Snippets to use
####################

#NFS folder sharing
#config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

####################
####################
config.vm.box = "ubuntu-13.10-server-amd64"
config.hostmanager.enabled = true
config.hostmanager.ignore_public_ip = false

    #public server
    config.vm.define "public".to_sym do |public_config|
        public_config.vm.box = "ubuntu-13.10-server-amd64"
        public_config.vm.hostname = "public.local"
        public_config.hostmanager.enabled = true
        public_config.vm.network :public_network, ip: "10.0.1.7"
        #set some machine-specific options	
        public_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
    
    #publicly accessible server
    config.vm.define "public".to_sym do |public_config|
        public_config.vm.box = "ubuntu-13.10-server-amd64"
        public_config.vm.hostname = "public.local"
        public_config.hostmanager.enabled = true
        public_config.vm.network :public_network, ip: "10.0.1.8"
        #set some machine-specific options	
        public_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
end
