Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing for Puppet modules and manifests
  #config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules" #:nfs => true
  #config.vm.synced_folder "manifests/", "/etc/puppet/manifests" #:nfs => true
  #config.vm.synced_folder "hieradata/", "/etc/puppet/environments/production/hieradata" #:nfs => true

  #Puppet provisioning scripts
  #phabricator_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master.sh"
  #phabricator_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"

  ####################
  ####################

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #Certificate Authority (CA) server
  config.vm.define "ca".to_sym do |ca_config|
    ca_config.vm.box = "ubuntu-13.10-server-amd64"
    ca_config.vm.hostname = "ca.local"
    ca_config.hostmanager.enabled = true
    ca_config.hostmanager.aliases = %w(ca ca.local)
    ca_config.vm.network :private_network, ip: "10.0.1.78"
    #set some machine-specific options	
    ca_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end  

  #SSL server
  config.vm.define "ssl".to_sym do |ssl_config|
    ssl_config.vm.box = "ubuntu-13.10-server-amd64"
    ssl_config.vm.hostname = "ssl.local"
    ssl_config.hostmanager.enabled = true
    ssl_config.hostmanager.aliases = %w(ssl ssl.local)
    ssl_config.vm.network :private_network, ip: "10.0.1.79"
    #set some machine-specific options	
    ssl_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
end