Vagrant.configure("2") do |config|
# All Vagrant configuration is done here. The most common configuration
# options are documented and commented below. For a complete reference,
# please see the online documentation at vagrantup.com.

####################
# Snippets to use
####################

#NFS folder sharing
#onfig.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

####################
####################
config.vm.box = "ubuntu-12.10-server-amd64"
config.hostmanager.enabled = true
config.hostmanager.ignore_private_ip = false

    #MySQL mysqlmaster
    config.vm.define "mysqlmaster".to_sym do |mysqlmaster_config|
        mysqlmaster_config.vm.box = "ubuntu-12.10-server-amd64"
        mysqlmaster_config.vm.hostname = "mysqlmaster.local"
        mysqlmaster_config.hostmanager.enabled = true
        mysqlmaster_config.vm.network :private_network, ip: "10.0.1.39"
        #set some machine-specific options	
        mysqlmaster_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
    
    #MySQL slave 1
    config.vm.define "mysqlslave1".to_sym do |mysqlslave1_config|
        mysqlslave1_config.vm.box = "ubuntu-12.10-server-amd64"
        mysqlslave1_config.vm.hostname = "mysqlslave1.local"
        mysqlslave1_config.hostmanager.enabled = true
        mysqlslave1_config.vm.network :private_network, ip: "10.0.1.38"
        #set some machine-specific options	
        mysqlslave1_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
    
    #MySQL slave 2
    config.vm.define "mysqlslave2".to_sym do |mysqlslave2_config|
        mysqlslave2_config.vm.box = "ubuntu-12.10-server-amd64"
        mysqlslave2_config.vm.hostname = "mysqlslave2.local"
        mysqlslave2_config.hostmanager.enabled = true
        mysqlslave2_config.vm.network :private_network, ip: "10.0.1.37"
        #set some machine-specific options	
        mysqlslave2_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
end
