Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################
  config.vm.box = "ubuntu-13.10-server-amd64"
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false

  #ganglia web server
  config.vm.define "gitlab".to_sym do |gitlab_config|
    gitlab_config.vm.box = "ubuntu-13.10-server-amd64"
    gitlab_config.vm.hostname = "gitlab.local"
    gitlab_config.hostmanager.enabled = true
    gitlab_config.vm.network :private_network, ip: "10.0.1.50"
    #set some machine-specific options	
    gitlab_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  #a ganglia client
  config.vm.define "gerrit".to_sym do |gerrit_config|
    gerrit_config.vm.box = "ubuntu-13.10-server-amd64"
    gerrit_config.vm.hostname = "gerrit.local"
    gerrit_config.hostmanager.enabled = true
    gerrit_config.vm.network :private_network, ip: "10.0.1.51"
    #set some machine-specific options	
    gerrit_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
end
