Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing for Puppet modules and manifests
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #PostgresQL server
  config.vm.define "postgres".to_sym do |postgres_config|
    postgres_config.vm.box = "ubuntu-13.04-server-amd64"
    postgres_config.vm.hostname = "postgres.local"
    postgres_config.hostmanager.enabled = true
    postgres_config.hostmanager.aliases = %w(postgres)
    postgres_config.vm.network :private_network, ip: "10.0.1.30"
    #set some machine-specific options	
    postgres_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
  
  #MySQL server
  config.vm.define "mysql".to_sym do |mysql_config|
    mysql_config.vm.box = "ubuntu-13.04-server-amd64"
    mysql_config.vm.hostname = "mysql.local"
    mysql_config.hostmanager.enabled = true
    mysql_config.hostmanager.aliases = %w(mysql)
    mysql_config.vm.network :private_network, ip: "10.0.1.31"
    #set some machine-specific options	
    mysql_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
  
  #MariaDB server
  config.vm.define "mariadb".to_sym do |mariadb_config|
    mariadb_config.vm.box = "ubuntu-13.04-server-amd64"
    mariadb_config.vm.hostname = "mariadb.local"
    mariadb_config.hostmanager.enabled = true
    mariadb_config.hostmanager.aliases = %w(mariadb)
    mariadb_config.vm.network :private_network, ip: "10.0.1.32"
    #set some machine-specific options	
    mariadb_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  #MongoDB server
  config.vm.define "mongodb".to_sym do |mongodb_config|
    mongodb_config.vm.box = "ubuntu-13.04-server-amd64"
    mongodb_config.vm.hostname = "mongodb.local"
    mongodb_config.hostmanager.enabled = true
    mongodb_config.hostmanager.aliases = %w(mongodb)
    mongodb_config.vm.network :private_network, ip: "10.0.1.33"
    #set some machine-specific options	
    mongodb_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end 
end