Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #An Ubuntu 14.04 utopic Puppet master machine
  config.vm.define "utopicpuppetmaster".to_sym do |utopicpuppetmaster_config|
    utopicpuppetmaster_config.vm.box = "ubuntu-14.10-server-amd64"
    utopicpuppetmaster_config.vm.hostname = "utopicpuppetmaster.local"
    utopicpuppetmaster_config.hostmanager.aliases = %w(master puppet master.local utopicpuppetmaster.local puppetboard.utopicpuppetmaster.local)
    utopicpuppetmaster_config.vm.network :private_network, ip: "10.0.1.70"
    #set some machine-specific options	
    utopicpuppetmaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    config.vm.synced_folder "hieradata", "/etc/puppet/environments/production/hieradata", :nfs => true
    #Puppet master provisioning script
  end

  #An Ubuntu 14.04 utopic Puppet agent machine
  config.vm.define "utopicpuppetagent".to_sym do |utopicpuppetagent_config|
    utopicpuppetagent_config.vm.box = "ubuntu-14.10-server-amd64"
    utopicpuppetagent_config.vm.hostname = "utopicpuppetagent.local"
    utopicpuppetagent_config.vm.network :private_network, ip: "10.0.1.71"
    #set some machine-specific options	
    utopicpuppetagent_config.vm.provider "virtualbox" do |v|
         #change the amount of RAM 
          v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  utopicpuppetagent_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_utopic_puppet_agent.sh"
  end
end
