Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #Puppet master and fail2ban machine
  config.vm.define "failmaster".to_sym do |failmaster_config|
    failmaster_config.vm.box = "ubuntu-14.04-server-amd64"
    failmaster_config.vm.hostname = "failmaster.local"
    failmaster_config.hostmanager.aliases = %w(master puppet master.local puppetboard.failmaster.local)
    failmaster_config.vm.network :private_network, ip: "10.0.1.70"
    #set some machine-specific options	
    failmaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    failmaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    failmaster_config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    failmaster_config.vm.synced_folder "hieradata", "/etc/puppet/environments/production/hieradata", :nfs => true
    #Puppet master provisioning script
    failmaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"
  end

  #A fail2ban client
  config.vm.define "failclient1".to_sym do |failclient1_config|
    failclient1_config.vm.box = "centos-6.6-amd64"
    failclient1_config.vm.hostname = "failclient1.local"
    failclient1_config.vm.network :private_network, ip: "10.0.1.71"
    #set some machine-specific options	
    failclient1_config.vm.provider "virtualbox" do |v|
         #change the amount of RAM 
          v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  failclient1_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #A fail2ban client
  config.vm.define "failclient2".to_sym do |failclient2_config|
    failclient2_config.vm.box = "ubuntu-14.04-server-amd64"
    failclient2_config.vm.hostname = "failclient2.local"
    failclient2_config.vm.network :private_network, ip: "10.0.1.72"
    #set some machine-specific options	
    failclient2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  failclient2_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #A fail2ban client
  config.vm.define "failclient3".to_sym do |failclient3_config|
    failclient3_config.vm.box = "centos-6.6-amd64"
    failclient3_config.vm.hostname = "failclient3.local"
    failclient3_config.vm.network :private_network, ip: "10.0.1.73"
    #set some machine-specific options	
    failclient3_config.vm.provider "virtualbox" do |v|
         #change the amount of RAM 
          v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  failclient3_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #A fail2ban client
  config.vm.define "failclient4".to_sym do |failclient4_config|
    failclient4_config.vm.box = "ubuntu-14.04-server-amd64"
    failclient4_config.vm.hostname = "failclient4.local"
    failclient4_config.vm.network :private_network, ip: "10.0.1.74"
    #set some machine-specific options	
    failclient4_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  failclient4_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end
end
