Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #gitlabmaster Puppet master
  config.vm.define "gitlabmaster".to_sym do |gitlabmaster_config|
    gitlabmaster_config.vm.box = "ubuntu-13.10-server-amd64"
    gitlabmaster_config.vm.hostname = "gitlabmaster.local"
    gitlabmaster_config.hostmanager.enabled = true
    gitlabmaster_config.hostmanager.aliases = %w(gitlabmaster.local puppet puppetboard.gitlabmaster.local)
    gitlabmaster_config.vm.network :private_network, ip: "10.0.1.49"
    #set some machine-specific options	
    gitlabmaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    gitlabmaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules", :nfs => true
    gitlabmaster_config.vm.synced_folder "manifests/", "/etc/puppet/manifests", :nfs => true
    gitlabmaster_config.vm.synced_folder "hieradata", "/etc/puppet/hieradata", :nfs => true
    #Puppet master provisioning script
    gitlabmaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master.sh"
  end

  #GitLab server
  config.vm.define "gitlab".to_sym do |gitlab_config|
    gitlab_config.vm.box = "ubuntu-13.10-server-amd64"
    gitlab_config.vm.hostname = "gitlab.local"
    gitlab_config.hostmanager.enabled = true
    gitlab_config.hostmanager.aliases = %w(gitlab.local)
    gitlab_config.vm.network :private_network, ip: "10.0.1.50"
    #set some machine-specific options	
    gitlab_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #Puppet agent provisioning script
    gitlab_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end

  #Gerrit server
  config.vm.define "gerrit".to_sym do |gerrit_config|
    gerrit_config.vm.box = "ubuntu-13.10-server-amd64"
    gerrit_config.vm.hostname = "gerrit.local"
    gerrit_config.hostmanager.enabled = true
    gerrit_config.vm.network :private_network, ip: "10.0.1.51"
    #set some machine-specific options	
    gerrit_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #Puppet agent provisioning script
    gerrit_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end
end
