Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules"
  config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests"
  config.vm.synced_folder "hieradata/", "/etc/puppet/environments/production/hieradata"

  ####################
  ####################
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #Amanda backup server
  config.vm.define "amandaserver".to_sym do |amandaserver_config|
    amandaserver_config.vm.box = "ubuntu-14.04-server-amd64"
    amandaserver_config.vm.hostname = "amandaserver.local"
    amandaserver_config.hostmanager.enabled = true
    amandaserver_config.hostmanager.aliases = %w(amandaserver.local puppet puppet.local)
    amandaserver_config.vm.network :private_network, ip: "10.0.1.52"
    #set some machine-specific options  
    amandaserver_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #amandaserver_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"
  end

  #CentOS Amanda backup client
  config.vm.define "client1".to_sym do |client1_config|
    client1_config.vm.box = "ubuntu-14.04-server-amd64"
    client1_config.vm.hostname = "client1.local"
    client1_config.hostmanager.enabled = true
    client1_config.vm.network :private_network, ip: "10.0.1.53"
    #set some machine-specific options  
    client1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #client1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #CentOS Amanda backup client
  config.vm.define "client2".to_sym do |client2_config|
    client2_config.vm.box = "centos-6.5-amd64"
    client2_config.vm.hostname = "client2.local"
    client2_config.hostmanager.enabled = true
    client2_config.vm.network :private_network, ip: "10.0.1.54"
    #set some machine-specific options  
    client2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #client2_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end
end