Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  config.vm.box = "ubuntu-13.10-server-amd64"
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.manage_host = true
  
 #puppet master
 config.vm.define "ntpmaster".to_sym do |ntpmaster_config|
	ntpmaster_config.vm.box = "ubuntu-13.10-server-amd64"
	ntpmaster_config.vm.hostname = "ntpmaster.local"
	ntpmaster_config.hostmanager.enabled = true
	ntpmaster_config.vm.network :private_network, ip: "10.0.1.80"
	#set some machine-specific options	
	ntpmaster_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
  
  #main NTP server
  config.vm.define "ntp1".to_sym do |ntp1_config|
	ntp1_config.vm.box = "ubuntu-13.10-server-amd64"
	ntp1_config.vm.hostname = "ntp1.local"
	ntp1_config.hostmanager.enabled = true
	ntp1_config.vm.network :private_network, ip: "10.0.1.81"
	#set some machine-specific options	
	ntp1_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
  
  #another NTP server
  config.vm.define "ntp2".to_sym do |ntp2_config|
	ntp2_config.vm.box = "debian-7.2-amd64"
	ntp2_config.vm.hostname = "ntp2.local"
	ntp2_config.hostmanager.enabled = true
	ntp2_config.vm.network :private_network, ip: "10.0.1.82"
	#set some machine-specific options	
	ntp2_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
  
  #a client machine
  config.vm.define "ntp3".to_sym do |ntp3_config|
	ntp3_config.vm.box = "centos-6.5-amd64"
	ntp3_config.vm.hostname = "ntp3.local"
	ntp3_config.hostmanager.enabled = true
	ntp3_config.vm.network :private_network, ip: "10.0.1.83"
	#set some machine-specific options	
	ntp3_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
end