Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  config.vm.box = "ubuntu-12.10-server-amd64"
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  
 #puppet master
 config.vm.define "puppet".to_sym do |puppet_config|
	puppet_config.vm.box = "ubuntu-12.10-server-amd64-puppetmaster"
	puppet_config.vm.hostname = "puppet"
	puppet_config.hostmanager.enabled = true
	puppet_config.vm.network :private_network, ip: "10.0.1.80"
	#set some machine-specific options	
	puppet_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    puppet_config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  end
  
  #main NTP server
  config.vm.define "ntp1".to_sym do |ntp1_config|
	ntp1_config.vm.box = "ubuntu-12.10-server-amd64"
	ntp1_config.vm.hostname = "ntp1"
	ntp1_config.hostmanager.enabled = true
	ntp1_config.vm.network :private_network, ip: "10.0.1.81"
	#set some machine-specific options	
	ntp1_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
  
  #another NTP server
  config.vm.define "ntp2".to_sym do |ntp2_config|
	ntp2_config.vm.box = "ubuntu-12.10-server-amd64"
	ntp2_config.vm.hostname = "ntp2"
	ntp2_config.hostmanager.enabled = true
	ntp2_config.vm.network :private_network, ip: "10.0.1.82"
	#set some machine-specific options	
	ntp2_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
  
  #a client machine
  config.vm.define "client1".to_sym do |client1_config|
	client1_config.vm.box = "ubuntu-12.10-server-amd64"
	client1_config.vm.hostname = "client1"
	client1_config.hostmanager.enabled = true
	client1_config.vm.network :private_network, ip: "10.0.1.83"
	#set some machine-specific options	
	client1_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
end