Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing example
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true

  #Ubuntu Jenkins master server and Puppet master
  config.vm.define "jenkinsmaster".to_sym do |jenkinsmaster_config|
    jenkinsmaster_config.vm.box = "ubuntu-13.10-server-amd64"
    jenkinsmaster_config.vm.hostname = "jenkinsmaster.local"
    jenkinsmaster_config.hostmanager.enabled = true
    jenkinsmaster_config.hostmanager.aliases = %w(puppetboard.jenkinsmaster.local jenkinsmaster puppet master)
    jenkinsmaster_config.vm.network :private_network, ip: "10.0.1.48"
    #set some machine-specific options	
    jenkinsmaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #Set up synced folders for Puppet code:
    jenkinsmaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    jenkinsmaster_config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    jenkinsmaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/hieradata", "/etc/puppet/environments/production/hieradata", :nfs => true
    jenkinsmaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master.sh"
  end
  
  #Ubuntu Jenkins master server
  config.vm.define "ubuntujenkins".to_sym do |ubuntujenkins_config|
    ubuntujenkins_config.vm.box = "ubuntu-13.10-server-amd64"
    ubuntujenkins_config.vm.hostname = "ubuntujenkins.local"
    ubuntujenkins_config.hostmanager.enabled = true
    ubuntujenkins_config.vm.network :private_network, ip: "10.0.1.49"
    #set some machine-specific options	
    ubuntujenkins_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    ubuntujenkins_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end
  
  #CentOS Jenkins master server
  config.vm.define "centosjenkins".to_sym do |centosjenkins_config|
    centosjenkins_config.vm.box = "centos-6.5-amd64"
    centosjenkins_config.vm.hostname = "centosjenkins.local"
    centosjenkins_config.hostmanager.enabled = true
    centosjenkins_config.hostmanager.aliases = %w(jenkins.centosjenkins.local)
    centosjenkins_config.vm.network :private_network, ip: "10.0.1.50"
    #set some machine-specific options	
    centosjenkins_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    centosjenkins_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #Jenkins worker
  config.vm.define "worker1".to_sym do |worker1_config|
    worker1_config.vm.box = "centos-6.5-amd64"
    worker1_config.vm.hostname = "worker1.local"
    worker1_config.hostmanager.enabled = true
    worker1_config.vm.network :private_network, ip: "10.0.1.51"
    #set some machine-specific options	
    worker1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    worker1_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #Jenkins worker
  config.vm.define "worker2".to_sym do |worker2_config|
    worker2_config.vm.box = "centos-6.5-amd64"
    worker2_config.vm.hostname = "worker2.local"
    worker2_config.hostmanager.enabled = true
    worker2_config.vm.network :private_network, ip: "10.0.1.52"
    #set some machine-specific options	
    worker2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    worker2_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #Jenkins worker
  config.vm.define "worker3".to_sym do |worker3_config|
    worker3_config.vm.box = "centos-6.5-amd64"
    worker3_config.vm.hostname = "worker3.local"
    worker3_config.hostmanager.enabled = true
    worker3_config.vm.network :private_network, ip: "10.0.1.53"
    #set some machine-specific options	
    worker3_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    worker3_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #Jenkins worker
  config.vm.define "worker4".to_sym do |worker4_config|
    worker4_config.vm.box = "centos-6.5-amd64"
    worker4_config.vm.hostname = "worker4.local"
    worker4_config.hostmanager.enabled = true
    worker4_config.vm.network :private_network, ip: "10.0.1.54"
    #set some machine-specific options	
    worker4_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    worker4_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end
end
