Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  config.vm.box = "centos-6.4-amd64"
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  
 #puppet master
 config.vm.define "netxdam".to_sym do |netxdam_config|
  netxdam_config.vm.box = "centos-6.4-amd64"
    netxdam_config.vm.hostname = "netxdam"
    netxdam_config.hostmanager.enabled = true
    netxdam_config.vm.network :private_network, ip: "10.0.1.69"
    #set some machine-specific options
    netxdam_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
end
