Vagrant.configure("2") do |config|
# All Vagrant configuration is done here. The most common configuration
# options are documented and commented below. For a complete reference,
# please see the online documentation at vagrantup.com.

####################
# Snippets to use
####################

#NFS folder sharing
#config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

####################
####################
config.vm.box = "ubuntu-14.04-server-amd64"
config.hostmanager.enabled = true
config.hostmanager.ignore_private_ip = false

    #Nginx web server
    config.vm.define "nginx".to_sym do |nginx_config|
        nginx_config.vm.box = "ubuntu-14.04-server-amd64"
        nginx_config.vm.hostname = "nginx.local"
        nginx_config.hostmanager.enabled = true
        nginx_config.vm.network :private_network, ip: "10.0.1.6"
        #set some machine-specific options	
        nginx_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM
            v.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
end
