Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing for Puppet modules and manifests
    #config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules" #:nfs => true
    #config.vm.synced_folder "manifests/", "/etc/puppet/manifests" #:nfs => true
    #config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/hieradata", "/etc/puppet/hieradata" #:nfs => true
    
    #Puppet provisioning scripts
    #vmname_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master.sh"
    #vmname_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"

  ####################
  ####################

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #An Ubuntu ReviewBoard server
  config.vm.define "reviewboardubuntu".to_sym do |reviewboardubuntu_config|
    #the base box we're using
    reviewboardubuntu_config.vm.box = "ubuntu-13.10-server-amd64"
    #the box's hostname
    reviewboardubuntu_config.vm.hostname = "reviewboardubuntu.local"
    #enable the hostmanager Vagrant plugin for this VM
    reviewboardubuntu_config.hostmanager.enabled = true
    #some aliases the hostmanager plugin will add to the hosts files of other VMs
    reviewboardubuntu_config.hostmanager.aliases = %w(reviewboardubuntu review.reviewboardubuntu review.reviewboardubuntu.local)
    #set a static IP
    reviewboardubuntu_config.vm.network :private_network, ip: "10.0.1.110"
    #set some machine-specific options	
    reviewboardubuntu_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
  
  #A CentOS ReviewBoard server
  config.vm.define "reviewboardcentos".to_sym do |reviewboardcentos_config|
    #the base box we're using
    reviewboardcentos_config.vm.box = "centos-6.5-amd64"
    #the box's hostname
    reviewboardcentos_config.vm.hostname = "reviewboardcentos.local"
    #enable the hostmanager Vagrant plugin for this VM
    reviewboardcentos_config.hostmanager.enabled = true
    #some aliases the hostmanager plugin will add to the hosts files of other VMs
    reviewboardcentos_config.hostmanager.aliases = %w(reviewboardcentos review.reviewboardcentos review.reviewboardcentos.local)
    #set a static IP
    reviewboardcentos_config.vm.network :private_network, ip: "10.0.1.111"
    #set some machine-specific options	
    reviewboardcentos_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
end