Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing for Puppet modules and manifests
    #config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules" #:nfs => true
    #config.vm.synced_folder "manifests/", "/etc/puppet/manifests" #:nfs => true
    #config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/hieradata", "/etc/puppet/hieradata" #:nfs => true
    
    #Puppet provisioning scripts
    #phabricator_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1304_puppet_master_script.sh"
    #phabricator_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1304_puppet_agent_script.sh"

  ####################
  ####################

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #Phabricator server
  config.vm.define "phabricator".to_sym do |phabricator_config|
    phabricator_config.vm.box = "ubuntu-13.04-server-amd64"
    phabricator_config.vm.hostname = "phabricator.local"
    phabricator_config.hostmanager.enabled = true
    phabricator_config.hostmanager.aliases = %w(phabricator)
    phabricator_config.vm.network :private_network, ip: "10.0.1.75"
    #set some machine-specific options	
    phabricator_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end  

  #Phabricator mail server
  config.vm.define "phabricatormail".to_sym do |phabricatormail_config|
    phabricatormail_config.vm.box = "ubuntu-13.04-server-amd64"
    phabricatormail_config.vm.hostname = "phabricatormail.local"
    phabricatormail_config.hostmanager.enabled = true
    phabricatormail_config.hostmanager.aliases = %w(phabricatormail)
    phabricatormail_config.vm.network :private_network, ip: "10.0.1.76"
    #set some machine-specific options	
    phabricatormail_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
end