Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  ####################
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true

  #Ubuntu Saucy Puppet master
  config.vm.define "saucymaster".to_sym do |saucymaster_config|
    saucymaster_config.vm.box = "ubuntu-14.04-server-amd64"
    saucymaster_config.vm.hostname = "saucymaster.local"
    saucymaster_config.hostmanager.aliases = %w(puppetboard.saucymaster.local saucymaster puppet master)
    saucymaster_config.hostmanager.enabled = true
    saucymaster_config.vm.network :private_network, ip: "10.0.1.80"
    #set some machine-specific options	
    saucymaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #Set up synced folders for Puppet code:
    saucymaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    saucymaster_config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    saucymaster_config.vm.synced_folder "hieradata/", "/etc/puppet/environments/production/hieradata", :nfs => true
    saucymaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"
  end
  
  #Ubuntu Trusty Puppet master
  config.vm.define "trustymaster".to_sym do |trustymaster_config|
    trustymaster_config.vm.box = "ubuntu-14.04-server-amd64"
    trustymaster_config.vm.hostname = "trustymaster.local"
    trustymaster_config.hostmanager.aliases = %w(puppetboard.trustymaster.local trustymaster puppet master)
    trustymaster_config.hostmanager.enabled = true
    trustymaster_config.vm.network :private_network, ip: "10.0.1.81"
    #set some machine-specific options	
    trustymaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #Set up synced folders for Puppet code:
    trustymaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    trustymaster_config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    trustymaster_config.vm.synced_folder "hieradata/", "/etc/puppet/environments/production/hieradata", :nfs => true
    trustymaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"
  end

  #Ubuntu Saucy Puppet agent
  config.vm.define "saucyagent".to_sym do |saucyagent_config|
    saucyagent_config.vm.box = "ubuntu-14.04-server-amd64"
    saucyagent_config.vm.hostname = "saucyagent.local"
    saucyagent_config.hostmanager.enabled = true
    saucyagent_config.vm.network :private_network, ip: "10.0.1.82"
    #set some machine-specific options	
    saucyagent_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    saucyagent_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end
  
  #Ubuntu Trusty Puppet agent
  config.vm.define "trustyagent".to_sym do |trustyagent_config|
    trustyagent_config.vm.box = "ubuntu-14.04-server-amd64"
    trustyagent_config.vm.hostname = "trustyagent.local"
    trustyagent_config.hostmanager.enabled = true
    trustyagent_config.vm.network :private_network, ip: "10.0.1.83"
    #set some machine-specific options	
    trustyagent_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    trustyagent_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #CentOS 6 Puppet master
  config.vm.define "centos6master".to_sym do |centos6master_config|
    centos6master_config.vm.box = "centos-6.6-amd64"
    centos6master_config.vm.hostname = "centos6master.local"
    centos6master_config.hostmanager.aliases = %w(puppetboard.centos6master.local centos6master puppet master)
    centos6master_config.hostmanager.enabled = true
    centos6master_config.vm.network :private_network, ip: "10.0.1.84"
    #set some machine-specific options	
    centos6master_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #Set up synced folders for Puppet code:
    centos6master_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    centos6master_config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    centos6master_config.vm.synced_folder "hieradata/", "/etc/puppet/environments/production/hieradata", :nfs => true
    centos6master_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_master.sh"
  end

  #Debian Puppet master
  config.vm.define "debianmaster".to_sym do |debianmaster_config|
    debianmaster_config.vm.box = "debian-7.4-amd64"
    debianmaster_config.vm.hostname = "debianmaster.local"
    debianmaster_config.hostmanager.aliases = %w(puppetboard.debianmaster.local debianmaster puppet master)
    debianmaster_config.hostmanager.enabled = true
    debianmaster_config.vm.network :private_network, ip: "10.0.1.85"
    #set some machine-specific options	
    debianmaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #Set up synced folders for Puppet code:
    debianmaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    debianmaster_config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    debianmaster_config.vm.synced_folder "hieradata/", "/etc/puppet/environments/production/hieradata", :nfs => true
    debianmaster_config.vm.provision :shell, :path => "../provisioning_scripts/debian_puppet_master.sh"
  end

end
