Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################
  config.vm.box = "ubuntu-13.04-server-amd64"
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true

  #Ubuntu Jenkins master server
  config.vm.define "ubuntujenkins".to_sym do |ubuntujenkins_config|
    ubuntujenkins_config.vm.box = "ubuntu-13.04-server-amd64"
    ubuntujenkins_config.vm.hostname = "ubuntujenkins.local"
    ubuntujenkins_config.hostmanager.enabled = true
    ubuntujenkins_config.vm.network :private_network, ip: "10.0.1.49"
    #set some machine-specific options	
    ubuntujenkins_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
  
  #CentOS Jenkins master server
  config.vm.define "centosjenkins".to_sym do |centosjenkins_config|
    centosjenkins_config.vm.box = "centos-6.4-amd64"
    centosjenkins_config.vm.hostname = "centosjenkins.local"
    centosjenkins_config.hostmanager.enabled = true
    centosjenkins_config.vm.network :private_network, ip: "10.0.1.48"
    #set some machine-specific options	
    centosjenkins_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  #Jenkins worker
  config.vm.define "worker1".to_sym do |worker1_config|
    worker1_config.vm.box = "ubuntu-13.04-server-amd64"
    worker1_config.vm.hostname = "worker1.local"
    worker1_config.hostmanager.enabled = true
    worker1_config.vm.network :private_network, ip: "10.0.1.40"
    #set some machine-specific options	
    worker1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end

  #Jenkins worker
  config.vm.define "worker2".to_sym do |worker2_config|
    worker2_config.vm.box = "ubuntu-13.04-server-amd64"
    worker2_config.vm.hostname = "worker2.local"
    worker2_config.hostmanager.enabled = true
    worker2_config.vm.network :private_network, ip: "10.0.1.41"
    #set some machine-specific options	
    worker2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end

  #Ubuntu Tomcat VM
  config.vm.define "ubuntutomcat".to_sym do |ubuntutomcat_config|
    ubuntutomcat_config.vm.box = "ubuntu-13.04-server-amd64"
    ubuntutomcat_config.vm.hostname = "ubuntutomcat.local"
    ubuntutomcat_config.hostmanager.enabled = true
    ubuntutomcat_config.vm.network :private_network, ip: "10.0.1.42"
    #set some machine-specific options	
    ubuntutomcat_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  #CentOS Tomcat VM
  config.vm.define "centostomcat".to_sym do |centostomcat_config|
    centostomcat_config.vm.box = "centos-6.4-amd64"
    centostomcat_config.vm.hostname = "centostomcat.local"
    centostomcat_config.hostmanager.enabled = true
    centostomcat_config.vm.network :private_network, ip: "10.0.1.43"
    #set some machine-specific options	
    centostomcat_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

end
