Vagrant.configure("2") do |config|
# All Vagrant configuration is done here. The most common configuration
# options are documented and commented below. For a complete reference,
# please see the online documentation at vagrantup.com.

####################
# Snippets to use
####################

#NFS folder sharing
#config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

####################
####################
config.vm.box = "ubuntu-13.04-server-amd64"
#vagrant-hostmanager plugin options
config.hostmanager.enabled = true
config.hostmanager.ignore_private_ip = false
#update the /etc/hosts of the host OS
config.hostmanager.manage_host = true

    #ganglia web server
    config.vm.define "jenkins".to_sym do |jenkins_config|
        jenkins_config.vm.box = "ubuntu-13.04-server-amd64"
        jenkins_config.vm.hostname = "jenkins.local"
        jenkins_config.hostmanager.enabled = true
        jenkins_config.vm.network :private_network, ip: "10.0.1.49"
        #set some machine-specific options	
        jenkins_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
  
    #ganglia metadata server
    config.vm.define "worker1".to_sym do |worker1_config|
        worker1_config.vm.box = "ubuntu-13.04-server-amd64"
        worker1_config.vm.hostname = "worker1.local"
        worker1_config.hostmanager.enabled = true
        worker1_config.vm.network :private_network, ip: "10.0.1.40"
        #set some machine-specific options	
        worker1_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end

    #a ganglia client
    config.vm.define "worker2".to_sym do |worker2_config|
        worker2_config.vm.box = "ubuntu-13.04-server-amd64"
        worker2_config.vm.hostname = "worker2.local"
        worker2_config.hostmanager.enabled = true
        worker2_config.vm.network :private_network, ip: "10.0.1.41"
        #set some machine-specific options	
        worker2_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "512"]
        end
    end

     #a ganglia client
    config.vm.define "worker3".to_sym do |worker3_config|
        worker3_config.vm.box = "ubuntu-13.04-server-amd64"
        worker3_config.vm.hostname = "worker3.local"
        worker3_config.hostmanager.enabled = true
        worker3_config.vm.network :private_network, ip: "10.0.1.42"
        #set some machine-specific options	
        worker3_config.vm.provider "virtualbox" do |v|
            #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "512"]
        end
    end

     #a ganglia client
    config.vm.define "worker4".to_sym do |worker4_config|
        worker4_config.vm.box = "ubuntu-13.04-server-amd64"
        worker4_config.vm.hostname = "worker4.local"
        worker4_config.hostmanager.enabled = true
        worker4_config.vm.network :private_network, ip: "10.0.1.43"
        #set some machine-specific options	
        worker4_config.vm.provider "virtualbox" do |v|
            #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "512"]
        end
    end
end
