Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules"
  config.vm.synced_folder "manifests/", "/etc/puppet/manifests"
  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/hieradata", "/etc/puppet/hieradata"

  ####################
  ####################
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true


  #Ubuntu Puppet master
  config.vm.define "puppet".to_sym do |puppet_config|
    puppet_config.vm.box = "ubuntu-13.10-server-amd64"
    puppet_config.vm.hostname = "puppet.local"
    puppet_config.hostmanager.enabled = true
    puppet_config.hostmanager.aliases = %w(puppet puppet.local)
    puppet_config.vm.network :private_network, ip: "10.0.1.150"
    #set some machine-specific options	
    puppet_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    puppet_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1310_puppet_master_script.sh"
  end

  #Ubuntu Serf agent VM
  config.vm.define "ubuntuserf".to_sym do |ubuntuserf_config|
    ubuntuserf_config.vm.box = "ubuntu-13.10-server-amd64"
    ubuntuserf_config.vm.hostname = "ubuntuserf.local"
    ubuntuserf_config.hostmanager.enabled = true
    ubuntuserf_config.hostmanager.aliases = %w(ubuntuserf.local puppet puppet.local)
    ubuntuserf_config.vm.network :private_network, ip: "10.0.1.151"
    #set some machine-specific options	
    ubuntuserf_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    ubuntuserf_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1310_puppet_agent_script.sh"
  end

  #CentOS Serf agent VM
  config.vm.define "centosserf".to_sym do |centosserf_config|
    centosserf_config.vm.box = "centos-6.5-amd64"
    centosserf_config.vm.hostname = "centosserf.local"
    centosserf_config.hostmanager.enabled = true
    centosserf_config.vm.network :private_network, ip: "10.0.1.152"
    #set some machine-specific options	
    centosserf_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    centosserf_config.vm.provision :shell, :path => "../provisioning_scripts/rhel_centos_puppet_agent_script.sh"
  end
end
