Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #LDAP server
  config.vm.define "ldap".to_sym do |ldap_config|
    ldap_config.vm.box = "ubuntu-13.04-server-amd64"
    ldap_config.vm.hostname = "ldap.local"
    ldap_config.hostmanager.enabled = true
    ldap_config.hostmanager.aliases = %w(directory.local)
    ldap_config.vm.network :private_network, ip: "10.0.1.20"
    #set some machine-specific options	
    ldap_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  #An Ubuntu LDAP client
  config.vm.define "ubuntuldapclient".to_sym do |ubuntuldapclient_config|
    ubuntuldapclient_config.vm.box = "ubuntu-13.04-server-amd64"
    ubuntuldapclient_config.vm.hostname = "ubuntuldapclient.local"
    ubuntuldapclient_config.hostmanager.enabled = true
    ubuntuldapclient_config.vm.network :private_network, ip: "10.0.1.21"
    #set some machine-specific options	
    ubuntuldapclient_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end

  #A CentOS LDAP client
  config.vm.define "centosldapclient".to_sym do |centosldapclient_config|
    centosldapclient_config.vm.box = "centos-6.4-amd64"
    centosldapclient_config.vm.hostname = "centosldapclient.local"
    centosldapclient_config.hostmanager.enabled = true
    centosldapclient_config.vm.network :private_network, ip: "10.0.1.22"
    #set some machine-specific options	
    centosldapclient_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
  
  #A web server VM to host LDAP web UIs
  config.vm.define "ldapweb".to_sym do |ldapweb_config|
    ldapweb_config.vm.box = "ubuntu-13.04-server-amd64"
    ldapweb_config.vm.hostname = "ldapweb.local"
    ldapweb_config.hostmanager.enabled = true
    ldapweb_config.hostmanager.aliases = %w(phpldapadmin.ldapweb.local)
    ldapweb_config.vm.network :private_network, ip: "10.0.1.23"
    #set some machine-specific options	
    ldapweb_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
end
