Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules"
  config.vm.synced_folder "manifests/", "/etc/puppet/manifests"
  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/hieradata", "/etc/puppet/hieradata"

  ####################
  ####################
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #Ubuntu Puppet master
  config.vm.define "master".to_sym do |master_config|
    master_config.vm.box = "ubuntu-13.10-server-amd64"
    master_config.vm.hostname = "master.local"
    master_config.hostmanager.enabled = true
    master_config.hostmanager.aliases = %w(master.local puppet puppet.local puppetdb.master.local puppetboard.master.local)
    master_config.vm.network :private_network, ip: "10.0.1.190"
    #set some machine-specific options	
    master_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    master_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master_script.sh"
  end

  #Puppet agent
  config.vm.define "agent1".to_sym do |agent1_config|
    agent1_config.vm.box = "ubuntu-13.10-server-amd64"
    agent1_config.vm.hostname = "agent1.local"
    agent1_config.hostmanager.enabled = true
    agent1_config.hostmanager.aliases = %w(agent1.local)
    agent1_config.vm.network :private_network, ip: "10.0.1.191"
    #set some machine-specific options	
    agent1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    agent1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end

  #Puppet agent
  config.vm.define "agent2".to_sym do |agent2_config|
    agent2_config.vm.box = "ubuntu-13.10-server-amd64"
    agent2_config.vm.hostname = "agent2.local"
    agent2_config.hostmanager.enabled = true
    agent2_config.hostmanager.aliases = %w(agent2.local)
    agent2_config.vm.network :private_network, ip: "10.0.1.192"
    #set some machine-specific options	
    agent2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    agent2_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end

  #Puppet agent
  config.vm.define "agent3".to_sym do |agent3_config|
    agent3_config.vm.box = "ubuntu-13.10-server-amd64"
    agent3_config.vm.hostname = "agent3.local"
    agent3_config.hostmanager.enabled = true
    agent3_config.hostmanager.aliases = %w(agent3.local)
    agent3_config.vm.network :private_network, ip: "10.0.1.193"
    #set some machine-specific options	
    agent3_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    agent3_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end

  #Puppet agent
  config.vm.define "agent4".to_sym do |agent4_config|
    agent4_config.vm.box = "ubuntu-13.10-server-amd64"
    agent4_config.vm.hostname = "agent4.local"
    agent4_config.hostmanager.enabled = true
    agent4_config.hostmanager.aliases = %w(agent4.local)
    agent4_config.vm.network :private_network, ip: "10.0.1.194"
    #set some machine-specific options	
    agent4_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    agent4_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end
end