Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing example
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true

  #Ubuntu SeLinux Puppet master
  config.vm.define "selinuxmaster".to_sym do |selinuxmaster_config|
    selinuxmaster_config.vm.box = "ubuntu-13.10-server-amd64"
    selinuxmaster_config.vm.hostname = "selinuxmaster.local"
    selinuxmaster_config.hostmanager.enabled = true
    selinuxmaster_config.hostmanager.aliases = %w(puppetboard.selinuxmaster.local selinuxmaster puppet master)
    selinuxmaster_config.vm.network :private_network, ip: "10.0.1.48"
    #set some machine-specific options	
    selinuxmaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #Set up synced folders for Puppet code:
    selinuxmaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    selinuxmaster_config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    selinuxmaster_config.vm.synced_folder "hieradata/", "/etc/puppet/environments/production/hieradata", :nfs => true
    selinuxmaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"
  end

  #CentOS SeLinux machine
  config.vm.define "selinux1".to_sym do |selinux1_config|
    selinux1_config.vm.box = "centos-6.5-amd64"
    selinux1_config.vm.hostname = "selinux1.local"
    selinux1_config.hostmanager.enabled = true
    selinux1_config.vm.network :private_network, ip: "10.0.1.51"
    #set some machine-specific options	
    selinux1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    selinux1_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #CentOS SeLinux machine
  config.vm.define "selinux2".to_sym do |selinux2_config|
    selinux2_config.vm.box = "centos-6.5-amd64"
    selinux2_config.vm.hostname = "selinux2.local"
    selinux2_config.hostmanager.enabled = true
    selinux2_config.vm.network :private_network, ip: "10.0.1.52"
    #set some machine-specific options	
    selinux2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    selinux2_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #CentOS SeLinux machine
  config.vm.define "selinux3".to_sym do |selinux3_config|
    selinux3_config.vm.box = "centos-6.5-amd64"
    selinux3_config.vm.hostname = "selinux3.local"
    selinux3_config.hostmanager.enabled = true
    selinux3_config.vm.network :private_network, ip: "10.0.1.53"
    #set some machine-specific options	
    selinux3_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    selinux3_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #CentOS SeLinux machine
  config.vm.define "selinux4".to_sym do |selinux4_config|
    selinux4_config.vm.box = "centos-6.5-amd64"
    selinux4_config.vm.hostname = "selinux4.local"
    selinux4_config.hostmanager.enabled = true
    selinux4_config.vm.network :private_network, ip: "10.0.1.54"
    #set some machine-specific options	
    selinux4_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    selinux4_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end
end
