Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  #master_config.vm.provision :shell, :inline => $rhel_centos_puppet_master_script  

  ####################
  ####################
  config.vm.box = "centos-6.5-amd64"
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  
 #a puppet master
 config.vm.define "master".to_sym do |master_config|
  master_config.vm.box = "centos-6.5-amd64"
	master_config.vm.hostname = "master"
	master_config.hostmanager.enabled = true
	#giving it 'puppet' as an alias so that the agents can connect to it with their default settings
	master_config.hostmanager.aliases = %w(puppet master)
	master_config.vm.network :private_network, ip: "10.0.1.60"
	#set some machine-specific options	
	master_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #master_config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
    master_config.vm.provision :shell, :inline => $rhel_centos_puppet_master_script
  end

 #a puppet agent
 config.vm.define "agent1".to_sym do |puppet_config|
  puppet_config.vm.box = "centos-6.5-amd64"
	puppet_config.vm.hostname = "agent1"
	puppet_config.hostmanager.enabled = true
	puppet_config.vm.network :private_network, ip: "10.0.1.61"
	#set some machine-specific options	
	puppet_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #puppet_config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
    puppet_config.vm.provision :shell, :inline => $rhel_centos_puppet_agent_script
  end
end