Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #onfig.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  config.vm.box = "centos-6.4-amd64"
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  
 #puppet
 config.vm.define "puppet".to_sym do |puppet_config|
  puppet_config.vm.box = "centos-6.4-amd64"
	puppet_config.vm.hostname = "puppet"
	puppet_config.hostmanager.enabled = true
	puppet_config.vm.network :private_network, ip: "10.0.1.60"
	#set some machine-specific options	
	puppet_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #puppet_config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
    puppet_config.vm.provision :shell, :inline => $rhel_centos_puppet_agent_script
  end
end

$rhel_centos_puppet_agent_script = <<SCRIPT
#! /bin/bash
echo Checking to see if the Puppet Labs RHEL/CentOS repo needs to be added...

if [ ! -f /home/vagrant/repos_added.txt ];
then    
    echo Adding repo...
	sudo rpm -ivh http://yum.puppetlabs.com/el/6/products/i386/puppetlabs-release-6-7.noarch.rpm
	echo DONE adding repo!
    echo Updating package lists with new repo...
	sudo yum check-update
	#Touch the repos_added file to skip this block the next time around
	touch /home/vagrant/repos_added.txt

else
	echo Skipping repo addition...
fi

echo Checking to see if the Puppet agent package needs to be installed...

if [ ! -f /home/vagrant/puppet_installed.txt ];
then
	echo Installing the Puppet agent...
	sudo yum install puppet
	echo DONE installing the Puppet agent!
	
	#Touch the puppet_installed.txt file to skip this block the next time around
	touch /home/vagrant/puppet_installed.txt
else
	echo Skipping Puppet agent package installation...
fi
SCRIPT

$puppet_agent_script = <<SCRIPT
#! /bin/bash
echo Checking to see if Puppet Labs Ubuntu repo needs to be added...
if [ ! -f /home/vagrant/repos_added.txt ];
then    
    echo Adding repo...

    echo Updating package lists with new repo...

    echo Installing Puppet...
	touch /home/vagrant/repos_added.txt
fi

SCRIPT

$puppet_master_script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
date > /etc/vagrant_provisioned_at2
wget -N http://apt.puppetlabs.com/puppetlabs-release-quantal.deb
sudo dpkg -i puppetlabs-release-quantal.deb
sudo apt-get update
sudo apt-get -y install puppet
SCRIPT
