Vagrant.configure("2") do |config|
# All Vagrant configuration is done here. The most common configuration
# options are documented and commented below. For a complete reference,
# please see the online documentation at vagrantup.com.

####################
# Snippets to use
####################

#NFS folder sharing
#config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

####################
####################
config.vm.box = "ubuntu-13.04-server-amd64"
config.hostmanager.enabled = true
config.hostmanager.ignore_private_ip = false

    #ganglia web server
    config.vm.define "graylog2".to_sym do |graylog2_config|
        graylog2_config.vm.box = "ubuntu-13.04-server-amd64"
        graylog2_config.vm.hostname = "graylog2.local"
        graylog2_config.hostmanager.enabled = true
        graylog2_config.vm.network :private_network, ip: "10.0.1.30"
        #set some machine-specific options	
        graylog2_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
    
    #a MongoDB server for Graylog2
    config.vm.define "graylogmongodb".to_sym do |graylogmongodb_config|
        graylogmongodb_config.vm.box = "ubuntu-13.04-server-amd64"
        graylogmongodb_config.vm.hostname = "graylogmongodb.local"
        graylogmongodb_config.hostmanager.enabled = true
        graylogmongodb_config.vm.network :private_network, ip: "10.0.1.29"
        #set some machine-specific options	
        graylogmongodb_config.vm.provider "virtualbox" do |v|
            #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end

    #a ganglia client
    config.vm.define "graylogclient1".to_sym do |graylogclient1_config|
        graylogclient1_config.vm.box = "ubuntu-13.04-server-amd64"
        graylogclient1_config.vm.hostname = "graylogclient1.local"
        graylogclient1_config.hostmanager.enabled = true
        graylogclient1_config.vm.network :private_network, ip: "10.0.1.31"
        #set some machine-specific options	
        graylogclient1_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "512"]
        end
    end

     #a ganglia client
    config.vm.define "graylogclient2".to_sym do |graylogclient2_config|
        graylogclient2_config.vm.box = "ubuntu-13.04-server-amd64"
        graylogclient2_config.vm.hostname = "graylogclient2.local"
        graylogclient2_config.hostmanager.enabled = true
        graylogclient2_config.vm.network :private_network, ip: "10.0.1.32"
        #set some machine-specific options	
        graylogclient2_config.vm.provider "virtualbox" do |v|
            #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "512"]
        end
    end

     #a ganglia client
    config.vm.define "graylogclient3".to_sym do |graylogclient3_config|
        graylogclient3_config.vm.box = "ubuntu-13.04-server-amd64"
        graylogclient3_config.vm.hostname = "graylogclient3.local"
        graylogclient3_config.hostmanager.enabled = true
        graylogclient3_config.vm.network :private_network, ip: "10.0.1.33"
        #set some machine-specific options	
        graylogclient3_config.vm.provider "virtualbox" do |v|
            #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "512"]
        end
    end
end
