Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules"
  config.vm.synced_folder "manifests/", "/etc/puppet/manifests"
  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/hieradata", "/etc/puppet/hieradata"

  ####################
  ####################
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #Ubuntu Scala VM
  config.vm.define "scalamaster".to_sym do |scalamaster_config|
    scalamaster_config.vm.box = "ubuntu-13.10-server-amd64"
    scalamaster_config.vm.hostname = "scalamaster.local"
    scalamaster_config.hostmanager.enabled = true
    scalamaster_config.hostmanager.aliases = %w(scalamaster.local puppet puppet.local scalapuppetboard.puppet.local scalapuppetdb.puppet.local)
    scalamaster_config.vm.network :private_network, ip: "10.0.1.55"
    #set some machine-specific options	
    scalamaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    scalamaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1310_puppet_master_script.sh"
  end

  #Ubuntu Scala VM
  config.vm.define "ubuntuscala".to_sym do |ubuntuscala_config|
    ubuntuscala_config.vm.box = "ubuntu-13.10-server-amd64"
    ubuntuscala_config.vm.hostname = "ubuntuscala.local"
    ubuntuscala_config.hostmanager.enabled = true
    ubuntuscala_config.hostmanager.aliases = %w(ubuntuscala.local puppet puppet.local)
    ubuntuscala_config.vm.network :private_network, ip: "10.0.1.56"
    #set some machine-specific options	
    ubuntuscala_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    ubuntuscala_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1310_puppet_agent_script.sh"
  end

  #CentOS Scala VM
  config.vm.define "centosscala".to_sym do |centosscala_config|
    centosscala_config.vm.box = "centos-6.5-amd64"
    centosscala_config.vm.hostname = "centosscala.local"
    centosscala_config.hostmanager.enabled = true
    centosscala_config.vm.network :private_network, ip: "10.0.1.57"
    #set some machine-specific options	
    centosscala_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    centosscala_config.vm.provision :shell, :path => "../provisioning_scripts/rhel_centos_puppet_agent_script.sh"
  end
end
