Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules"
  config.vm.synced_folder "manifests/", "/etc/puppet/manifests"
  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/hieradata", "/etc/puppet/hieradata"

  ####################
  ####################

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #A mailserver
  config.vm.define "mailserver1".to_sym do |mailserver1_config|
    mailserver1_config.vm.box = "ubuntu-13.10-server-amd64"
    mailserver1_config.vm.hostname = "mailserver1.local"
    mailserver1_config.hostmanager.enabled = true
    #giving it 'puppet' as an alias so that the agents can connect to it with their default settings
    mailserver1_config.hostmanager.aliases = %w(mailserver1 puppet puppet.local webmail.mailserver1.local)
    mailserver1_config.vm.network :private_network, ip: "10.0.1.190"
    #set some machine-specific options	
    mailserver1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    mailserver1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master_script.sh"
  end

  #Another mail server
  config.vm.define "mailserver2".to_sym do |mailserver2_config|
    mailserver2_config.vm.box = "ubuntu-13.10-server-amd64"
    mailserver2_config.vm.hostname = "mailserver2.local"
    mailserver2_config.hostmanager.enabled = true
    mailserver2_config.vm.network :private_network, ip: "10.0.1.191"
    #set some machine-specific options	
    mailserver2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    mailserver2_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent_script.sh.sh"
  end
end
