Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #Puppet master
  config.vm.define "zookeepermaster".to_sym do |zookeepermaster_config|
    zookeepermaster_config.vm.box = "ubuntu-14.04-server-amd64"
    zookeepermaster_config.vm.hostname = "zookeepermaster.local"
    zookeepermaster_config.hostmanager.aliases = %w(master puppet master.local puppetboard.zookeepermaster.local puppetexplorer.zookeepermaster.local)
    zookeepermaster_config.vm.network :private_network, ip: "10.0.1.110"
    #set some machine-specific options	
    zookeepermaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #NFS folder sharing for Puppet modules and manifests
    zookeepermaster_config.vm.synced_folder "production/", "/etc/puppet/environments/production", :nfs => true
    zookeepermaster_config.vm.synced_folder "~/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    zookeepermaster_config.vm.synced_folder "hieradata/", "/etc/puppet/hieradata", :nfs => true
    zookeepermaster_config.vm.synced_folder "files/", "/etc/puppet/files", :nfs => true
    #Puppet master provisioning script
    zookeepermaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"
  end

  #A CentOS 7 machine running Zookeeper:
  config.vm.define "zookeeper1".to_sym do |zookeeper1_config|
    zookeeper1_config.vm.box = "centos-7.0-amd64"
    zookeeper1_config.vm.hostname = "zookeeper1.local"
    zookeeper1_config.vm.network :private_network, ip: "10.0.1.111"
    #set some machine-specific options	
    zookeeper1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  zookeeper1_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #A CentOS 7 machine running Zookeeper:
  config.vm.define "zookeeper2".to_sym do |zookeeper2_config|
    zookeeper2_config.vm.box = "centos-7.0-amd64"
    zookeeper2_config.vm.hostname = "zookeeper2.local"
    zookeeper2_config.vm.network :private_network, ip: "10.0.1.112"
    #set some machine-specific options	
    zookeeper2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    zookeeper2_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #A CentOS 7 machine running Zookeeper:
  config.vm.define "zookeeper3".to_sym do |zookeeper3_config|
    zookeeper3_config.vm.box = "centos-7.0-amd64"
    zookeeper3_config.vm.hostname = "zookeeper3.local"
    zookeeper3_config.vm.network :private_network, ip: "10.0.1.113"
    #set some machine-specific options	
    zookeeper3_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    zookeeper3_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #A machine running...
  #...Riemann, InfluxDB and Grafana for metrics:
  #...Logstash, Elasticsearch and Kibana for logging
  #...Postfix and Dovecot for testing getting email alerts
  config.vm.define "zookeepermonitoring".to_sym do |zookeepermonitoring_config|
    zookeepermonitoring_config.vm.box = "ubuntu-14.04-server-amd64"
    zookeepermonitoring_config.vm.hostname = "zookeepermonitoring.local"
    zookeepermonitoring_config.hostmanager.aliases = %w(zookeepermonitoring grafana.zookeepermonitoring.local kibana3.zookeepermonitoring.local kibana.zookeepermonitoring.local)
    zookeepermonitoring_config.vm.network :private_network, ip: "10.0.1.115"
    #set some machine-specific options	
    zookeepermonitoring_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #Puppet agent provisioning script
	  zookeepermonitoring_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end
end
