Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #An Ubuntu rsyslog server
  config.vm.define "logstash".to_sym do |logstash_config|
    logstash_config.vm.box = "ubuntu-13.04-server-amd64"
    logstash_config.vm.hostname = "logstash.local"
    logstash_config.hostmanager.enabled = true
    #giving it 'puppet' as an alias so that the agents can connect to it with their default settings
    logstash_config.hostmanager.aliases = %w(logstash)
    logstash_config.vm.network :private_network, ip: "10.0.1.90"
    #set some machine-specific options	
    logstash_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  #An Elasticsearch node
  config.vm.define "logelasticsearch1".to_sym do |elasticsearch1_config|
    elasticsearch1_config.vm.box = "ubuntu-13.04-server-amd64"
    elasticsearch1_config.vm.hostname = "elasticsearch1.local"
    elasticsearch1_config.hostmanager.enabled = true
    elasticsearch1_config.vm.network :private_network, ip: "10.0.1.91"
    #set some machine-specific options	
    elasticsearch1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end

  #An Elasticsearch node
  config.vm.define "logelasticsearch2".to_sym do |elasticsearch2_config|
    elasticsearch2_config.vm.box = "ubuntu-13.04-server-amd64"
    elasticsearch2_config.vm.hostname = "elasticsearch2.local"
    elasticsearch2_config.hostmanager.enabled = true
    elasticsearch2_config.vm.network :private_network, ip: "10.0.1.92"
    #set some machine-specific options	
    elasticsearch2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
end