Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing
  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules"
  config.vm.synced_folder "manifests/", "/etc/puppet/manifests"
  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/hieradata", "/etc/puppet/hieradata"

  ####################
  ####################

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #An Ubuntu rsyslog server
  config.vm.define "logstash".to_sym do |logstash_config|
    logstash_config.vm.box = "ubuntu-13.10-server-amd64"
    logstash_config.vm.hostname = "logstash.local"
    logstash_config.hostmanager.enabled = true
    #giving it 'puppet' as an alias so that the agents can connect to it with their default settings
    logstash_config.hostmanager.aliases = %w(logstash)
    logstash_config.vm.network :private_network, ip: "10.0.1.140"
    #set some machine-specific options	
    logstash_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    logstash_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1310_puppet_agent_script.sh"
  end

  #An Elasticsearch node
  config.vm.define "elasticsearch1".to_sym do |elasticsearch1_config|
    elasticsearch1_config.vm.box = "ubuntu-13.10-server-amd64"
    elasticsearch1_config.vm.hostname = "elasticsearch1.local"
    elasticsearch1_config.hostmanager.enabled = true
    elasticsearch1_config.vm.network :private_network, ip: "10.0.1.141"
    #set some machine-specific options	
    elasticsearch1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    elasticsearch1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1310_puppet_agent_script.sh"
  end

  #An Elasticsearch node
  config.vm.define "elasticsearch2".to_sym do |elasticsearch2_config|
    elasticsearch2_config.vm.box = "ubuntu-13.10-server-amd64"
    elasticsearch2_config.vm.hostname = "elasticsearch2.local"
    elasticsearch2_config.hostmanager.enabled = true
    elasticsearch2_config.vm.network :private_network, ip: "10.0.1.142"
    #set some machine-specific options	
    elasticsearch2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    elasticsearch2_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1310_puppet_agent_script.sh"
  end
  
#   #An Elasticsearch node
#   config.vm.define "elasticsearch3".to_sym do |elasticsearch3_config|
#     elasticsearch3_config.vm.box = "ubuntu-13.10-server-amd64"
#     elasticsearch3_config.vm.hostname = "elasticsearch3.local"
#     elasticsearch3_config.hostmanager.enabled = true
#     elasticsearch3_config.vm.network :private_network, ip: "10.0.1.144"
#     #set some machine-specific options	
#     elasticsearch3_config.vm.provider "virtualbox" do |v|
#       #change the amount of RAM 
#       v.customize ["modifyvm", :id, "--memory", "512"]
#     end
#     elasticsearch3_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1310_puppet_agent_script.sh"
#   end
#   
#   #An Elasticsearch node
#   config.vm.define "elasticsearch4".to_sym do |elasticsearch4_config|
#     elasticsearch4_config.vm.box = "ubuntu-13.10-server-amd64"
#     elasticsearch4_config.vm.hostname = "elasticsearch4.local"
#     elasticsearch4_config.hostmanager.enabled = true
#     elasticsearch4_config.vm.network :private_network, ip: "10.0.1.145"
#     #set some machine-specific options	
#     elasticsearch4_config.vm.provider "virtualbox" do |v|
#       #change the amount of RAM 
#       v.customize ["modifyvm", :id, "--memory", "512"]
#     end
#     elasticsearch4_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1310_puppet_agent_script.sh"
#   end
  
  #A web server for Kibana 3
  config.vm.define "kibanathree".to_sym do |kibanathree_config|
    kibanathree_config.vm.box = "ubuntu-13.10-server-amd64"
    kibanathree_config.vm.hostname = "kibanathree.local"
    kibanathree_config.hostmanager.aliases = %w(dashboard.kibanathree.local)
    kibanathree_config.hostmanager.enabled = true
    kibanathree_config.vm.network :private_network, ip: "10.0.1.143"
    #set some machine-specific options	
    kibanathree_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    kibanathree_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1310_puppet_agent_script.sh"
  end

  #An rsyslog client
  config.vm.define "rsyslog1".to_sym do |rsyslog1_config|
    rsyslog1_config.vm.box = "ubuntu-13.10-server-amd64"
    rsyslog1_config.vm.hostname = "rsyslog1.local"
    rsyslog1_config.hostmanager.aliases = %w(rsyslog1.local)
    rsyslog1_config.hostmanager.enabled = true
    rsyslog1_config.vm.network :private_network, ip: "10.0.1.151"
    #set some machine-specific options	
    rsyslog1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    rsyslog1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1310_puppet_agent_script.sh"
  end

  #An rsyslog client
  config.vm.define "rsyslog2".to_sym do |rsyslog2_config|
    rsyslog2_config.vm.box = "ubuntu-13.10-server-amd64"
    rsyslog2_config.vm.hostname = "rsyslog2.local"
    rsyslog2_config.hostmanager.aliases = %w(rsyslog2.local)
    rsyslog2_config.hostmanager.enabled = true
    rsyslog2_config.vm.network :private_network, ip: "10.0.1.152"
    #set some machine-specific options	
    rsyslog2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
  rsyslog2_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1310_puppet_agent_script.sh"
  end
end
