Vagrant.configure("2") do |config|
# All Vagrant configuration is done here. The most common configuration
# options are documented and commented below. For a complete reference,
# please see the online documentation at vagrantup.com.

####################
# Snippets to use
####################

#NFS folder sharing
#onfig.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

####################
####################
config.vm.box = "ubuntu-12.10-server-amd64"
config.hostmanager.enabled = true
config.hostmanager.ignore_private_ip = false

    #ganglia web server
    config.vm.define "gangliaweb".to_sym do |gangliaweb_config|
        gangliaweb_config.vm.box = "ubuntu-12.10-server-amd64"
        gangliaweb_config.vm.hostname = "gangliaweb.local"
        gangliaweb_config.hostmanager.enabled = true
        gangliaweb_config.vm.network :private_network, ip: "10.0.1.49"
        #set some machine-specific options	
        gangliaweb_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
  
    #ganglia metadata server
    config.vm.define "gangliameta".to_sym do |gangliameta_config|
        gangliameta_config.vm.box = "ubuntu-12.10-server-amd64"
        gangliameta_config.vm.hostname = "gangliameta.local"
        gangliameta_config.hostmanager.enabled = true
        gangliameta_config.vm.network :private_network, ip: "10.0.1.50"
        #set some machine-specific options	
        gangliameta_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end

    #a ganglia client
    config.vm.define "gangliaclient1".to_sym do |gangliaclient1_config|
        gangliaclient1_config.vm.box = "ubuntu-12.10-server-amd64"
        gangliaclient1_config.vm.hostname = "gangliaclient1.local"
        gangliaclient1_config.hostmanager.enabled = true
        gangliaclient1_config.vm.network :private_network, ip: "10.0.1.51"
        #set some machine-specific options	
        gangliaclient1_config.vm.provider "virtualbox" do |v|
           #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "512"]
        end
    end

     #a ganglia client
    config.vm.define "gangliaclient2".to_sym do |gangliaclient2_config|
        gangliaclient2_config.vm.box = "ubuntu-12.10-server-amd64"
        gangliaclient2_config.vm.hostname = "gangliaclient2.local"
        gangliaclient2_config.hostmanager.enabled = true
        gangliaclient2_config.vm.network :private_network, ip: "10.0.1.52"
        #set some machine-specific options	
        gangliaclient2_config.vm.provider "virtualbox" do |v|
            #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "512"]
        end
    end

     #a ganglia client
    config.vm.define "gangliaclient3".to_sym do |gangliaclient3_config|
        gangliaclient3_config.vm.box = "ubuntu-13.04-server-amd64"
        gangliaclient3_config.vm.hostname = "gangliaclient3.local"
        gangliaclient3_config.hostmanager.enabled = true
        gangliaclient3_config.vm.network :private_network, ip: "10.0.1.53"
        #set some machine-specific options	
        gangliaclient3_config.vm.provider "virtualbox" do |v|
            #change the amount of RAM 
            v.customize ["modifyvm", :id, "--memory", "512"]
        end
    end
end
