Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #onfig.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  config.vm.box = "centos-6.4-amd64"
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  
 #ganglia server
config.vm.define "gangliaserver".to_sym do |gangliaserver_config|
	gangliaserver_config.vm.box = "centos-6.4-amd64"
	gangliaserver_config.vm.hostname = "ganglia.local"
	gangliaserver_config.hostmanager.enabled = true
	#giving it 'puppet' as an alias so that the agents can connect to it with their default settings
	gangliaserver_config.hostmanager.aliases = %w(ganglia)
	gangliaserver_config.vm.network :private_network, ip: "10.0.1.50"
	#set some machine-specific options	
	gangliaserver_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "1024"]
    end
end

#a ganglia client
config.vm.define "gangliaclient1".to_sym do |gangliaclient1_config|
	gangliaclient1_config.vm.box = "centos-6.4-amd64"
	gangliaclient1_config.vm.hostname = "gangliaclient1.local"
	gangliaclient1_config.hostmanager.enabled = true
	gangliaclient1_config.vm.network :private_network, ip: "10.0.1.51"
	#set some machine-specific options	
	gangliaclient1_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
	end
end

 #a ganglia client
config.vm.define "gangliaclient2".to_sym do |gangliaclient2_config|
	gangliaclient2_config.vm.box = "centos-6.4-amd64"
	gangliaclient2_config.vm.hostname = "gangliaclient2.local"
	gangliaclient2_config.hostmanager.enabled = true
	gangliaclient2_config.vm.network :private_network, ip: "10.0.1.52"
	#set some machine-specific options	
	gangliaclient2_config.vm.provider "virtualbox" do |v|
    	#change the amount of RAM 
    	v.customize ["modifyvm", :id, "--memory", "512"]
    end
end
end
