Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules"
  config.vm.synced_folder "manifests/", "/etc/puppet/manifests"
  config.vm.synced_folder "hieradata/", "/etc/puppet/hieradata"

  ####################
  ####################
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #Puppet master
  config.vm.define "gradlemaster".to_sym do |gradlemaster_config|
    gradlemaster_config.vm.box = "ubuntu-13.10-server-amd64"
    gradlemaster_config.vm.hostname = "gradlemaster.local"
    gradlemaster_config.hostmanager.enabled = true
    gradlemaster_config.hostmanager.aliases = %w(gradlemaster gradlemaster.local puppet puppet.local gradlepuppetboard.puppet.local gradlepuppetdb.puppet.local)
    gradlemaster_config.vm.network :private_network, ip: "10.0.1.52"
    #set some machine-specific options	
    gradlemaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    gradlemaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master.sh"
  end

  #Ubuntu Gradle VM
  config.vm.define "ubuntugradle".to_sym do |ubuntugradle_config|
    ubuntugradle_config.vm.box = "ubuntu-6.5-amd64"
    ubuntugradle_config.vm.hostname = "ubuntugradle.local"
    ubuntugradle_config.hostmanager.enabled = true
    ubuntugradle_config.vm.network :private_network, ip: "10.0.1.53"
    #set some machine-specific options	
    ubuntugradle_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    ubuntugradle_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end

  #CentOS Gradle VM
  config.vm.define "centosgradle".to_sym do |centosgradle_config|
    centosgradle_config.vm.box = "centos-6.5-amd64"
    centosgradle_config.vm.hostname = "centosgradle.local"
    centosgradle_config.hostmanager.enabled = true
    centosgradle_config.vm.network :private_network, ip: "10.0.1.54"
    #set some machine-specific options	
    centosgradle_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    centosgradle_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end
end
