Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing for Puppet modules and manifests
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #Puppet master and PuppetDB server
  config.vm.define "icinga2master".to_sym do |icinga2master_config|
    icinga2master_config.vm.box = "ubuntu-14.04-server-amd64"
    icinga2master_config.vm.hostname = "icinga2master.local"
    icinga2master_config.hostmanager.enabled = true
    icinga2master_config.hostmanager.aliases = %w(puppetboard.icinga2master.local puppetexplorer.icinga2master.local icinga2master puppet master)
    icinga2master_config.vm.network :private_network, ip: "10.0.1.80"
    #set some machine-specific options	
    icinga2master_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    icinga2master_config.vm.synced_folder "production/", "/etc/puppet/environments/production", :nfs => true
    icinga2master_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    #icinga2master_config.vm.synced_folder "hieradata/", "/etc/puppet/environments/production/hieradata", :nfs => true
    icinga2master_config.vm.synced_folder "files/", "/etc/puppet/files", :nfs => true
    #Puppet master provisioning script
    icinga2master_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"  
  end  

  #An Ubuntu 14.04 Icinga 2 server
  config.vm.define "trustyicinga2server".to_sym do |trustyicinga2server_config|
    trustyicinga2server_config.vm.box = "ubuntu-14.04-server-amd64"
    trustyicinga2server_config.vm.hostname = "trustyicinga2server.local"
    trustyicinga2server_config.hostmanager.enabled = true
    trustyicinga2server_config.hostmanager.aliases = %w(trustyicinga2server)
    trustyicinga2server_config.vm.network :private_network, ip: "10.0.1.81"
    #set some machine-specific options	
    trustyicinga2server_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    trustyicinga2server_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #An Ubuntu 14.10 Icinga 2 server
  config.vm.define "utopicicinga2server".to_sym do |utopicicinga2server_config|
    utopicicinga2server_config.vm.box = "ubuntu-14.10-server-amd64"
    utopicicinga2server_config.vm.hostname = "utopicicinga2server.local"
    utopicicinga2server_config.hostmanager.enabled = true
    utopicicinga2server_config.hostmanager.aliases = %w(utopicicinga2server)
    utopicicinga2server_config.vm.network :private_network, ip: "10.0.1.82"
    #set some machine-specific options	
    utopicicinga2server_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    utopicicinga2server_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #An Ubuntu 12.04 Icinga 2 server
  config.vm.define "preciseicinga2server".to_sym do |preciseicinga2server_config|
    preciseicinga2server_config.vm.box = "ubuntu-12.04-server-amd64"
    preciseicinga2server_config.vm.hostname = "preciseicinga2server.local"
    preciseicinga2server_config.hostmanager.enabled = true
    preciseicinga2server_config.hostmanager.aliases = %w(preciseicinga2server)
    preciseicinga2server_config.vm.network :private_network, ip: "10.0.1.83"
    #set some machine-specific options	
    preciseicinga2server_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    preciseicinga2server_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #A CentOS 6 Icinga 2 server
  config.vm.define "centos6icinga2server".to_sym do |centos6icinga2server_config|
    centos6icinga2server_config.vm.box = "centos-6.6-amd64"
    centos6icinga2server_config.vm.hostname = "centos6icinga2server.local"
    centos6icinga2server_config.hostmanager.enabled = true
    centos6icinga2server_config.hostmanager.aliases = %w(centos6icinga2server)
    centos6icinga2server_config.vm.network :private_network, ip: "10.0.1.84"
    #set some machine-specific options	
    centos6icinga2server_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    centos6icinga2server_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #A CentOS 7 Icinga 2 server
  config.vm.define "centos7icinga2server".to_sym do |centos7icinga2server_config|
    centos7icinga2server_config.vm.box = "centos-7.0-amd64"
    centos7icinga2server_config.vm.hostname = "centos7icinga2server.local"
    centos7icinga2server_config.hostmanager.enabled = true
    centos7icinga2server_config.hostmanager.aliases = %w(centos7icinga2server)
    centos7icinga2server_config.vm.network :private_network, ip: "10.0.1.85"
    #set some machine-specific options	
    centos7icinga2server_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    centos7icinga2server_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #A Debian 7 Icinga 2 server
  config.vm.define "debian7icinga2server".to_sym do |debian7icinga2server_config|
    debian7icinga2server_config.vm.box = "debian-7.8-amd64"
    debian7icinga2server_config.vm.hostname = "debian7icinga2server.local"
    debian7icinga2server_config.hostmanager.enabled = true
    debian7icinga2server_config.vm.network :private_network, ip: "10.0.1.86"
    debian7icinga2server_config.vm.provider "virtualbox" do |v| 	
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    debian7icinga2server_config.vm.provision :shell, :path => "../provisioning_scripts/debian_puppet_agent.sh"
  end

  #An Ubuntu 14.04 Icinga 2 server
  config.vm.define "trustyicinga2node".to_sym do |trustyicinga2node_config|
    trustyicinga2node_config.vm.box = "ubuntu-14.04-server-amd64"
    trustyicinga2node_config.vm.hostname = "trustyicinga2node.local"
    trustyicinga2node_config.hostmanager.enabled = true
    trustyicinga2node_config.hostmanager.aliases = %w(trustyicinga2node)
    trustyicinga2node_config.vm.network :private_network, ip: "10.0.1.87"
    #set some machine-specific options	
    trustyicinga2node_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    trustyicinga2node_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #An Ubuntu 14.10 Icinga 2 server
  config.vm.define "utopicicinga2node".to_sym do |utopicicinga2node_config|
    utopicicinga2node_config.vm.box = "ubuntu-14.10-server-amd64"
    utopicicinga2node_config.vm.hostname = "utopicicinga2node.local"
    utopicicinga2node_config.hostmanager.enabled = true
    utopicicinga2node_config.hostmanager.aliases = %w(utopicicinga2node)
    utopicicinga2node_config.vm.network :private_network, ip: "10.0.1.88"
    #set some machine-specific options	
    utopicicinga2node_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    utopicicinga2node_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #An Ubuntu 12.04 Icinga 2 server
  config.vm.define "preciseicinga2node".to_sym do |preciseicinga2node_config|
    preciseicinga2node_config.vm.box = "ubuntu-12.04-server-amd64"
    preciseicinga2node_config.vm.hostname = "preciseicinga2node.local"
    preciseicinga2node_config.hostmanager.enabled = true
    preciseicinga2node_config.hostmanager.aliases = %w(preciseicinga2node)
    preciseicinga2node_config.vm.network :private_network, ip: "10.0.1.89"
    #set some machine-specific options	
    preciseicinga2node_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    preciseicinga2node_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #A CentOS 6 Icinga 2 server
  config.vm.define "centos6icinga2node".to_sym do |centos6icinga2node_config|
    centos6icinga2node_config.vm.box = "centos-6.6-amd64"
    centos6icinga2node_config.vm.hostname = "centos6icinga2node.local"
    centos6icinga2node_config.hostmanager.enabled = true
    centos6icinga2node_config.hostmanager.aliases = %w(centos6icinga2node)
    centos6icinga2node_config.vm.network :private_network, ip: "10.0.1.90"
    #set some machine-specific options	
    centos6icinga2node_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    centos6icinga2node_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #A CentOS 7 Icinga 2 server
  config.vm.define "centos7icinga2node".to_sym do |centos7icinga2node_config|
    centos7icinga2node_config.vm.box = "centos-7.0-amd64"
    centos7icinga2node_config.vm.hostname = "centos7icinga2node.local"
    centos7icinga2node_config.hostmanager.enabled = true
    centos7icinga2node_config.hostmanager.aliases = %w(centos7icinga2node)
    centos7icinga2node_config.vm.network :private_network, ip: "10.0.1.91"
    #set some machine-specific options	
    centos7icinga2node_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    centos7icinga2node_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #A Debian 7 Icinga 2 server
  config.vm.define "debian7icinga2node".to_sym do |debian7icinga2node_config|
    debian7icinga2node_config.vm.box = "debian-7.8-amd64"
    debian7icinga2node_config.vm.hostname = "debian7icinga2node.local"
    debian7icinga2node_config.hostmanager.enabled = true
    debian7icinga2node_config.vm.network :private_network, ip: "10.0.1.92"
    debian7icinga2node_config.vm.provider "virtualbox" do |v| 	
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    debian7icinga2node_config.vm.provision :shell, :path => "../provisioning_scripts/debian_puppet_agent.sh"
  end


  #An Ubuntu 14.04 Icinga 2 client
  config.vm.define "trustyicinga2nrpeclient".to_sym do |trustyicinga2nrpeclient_config|
    trustyicinga2nrpeclient_config.vm.box = "ubuntu-14.04-server-amd64"
    trustyicinga2nrpeclient_config.vm.hostname = "trustyicinga2nrpeclient.local"
    trustyicinga2nrpeclient_config.hostmanager.enabled = true
    trustyicinga2nrpeclient_config.vm.network :private_network, ip: "10.0.1.93"
    #set some machine-specific options	
    trustyicinga2nrpeclient_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    trustyicinga2nrpeclient_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #An Ubuntu 14.10 Icinga 2 client
  config.vm.define "utopicicinga2nrpeclient".to_sym do |utopicicinga2nrpeclient_config|
    utopicicinga2nrpeclient_config.vm.box = "ubuntu-14.10-server-amd64"
    utopicicinga2nrpeclient_config.vm.hostname = "utopicicinga2nrpeclient.local"
    utopicicinga2nrpeclient_config.hostmanager.enabled = true
    utopicicinga2nrpeclient_config.vm.network :private_network, ip: "10.0.1.94"
    #set some machine-specific options	
    utopicicinga2nrpeclient_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    utopicicinga2nrpeclient_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #An Ubuntu 12.04 Icinga 2 client
  config.vm.define "preciseicinga2nrpeclient".to_sym do |preciseicinga2nrpeclient_config|
    preciseicinga2nrpeclient_config.vm.box = "ubuntu-12.04-server-amd64"
    preciseicinga2nrpeclient_config.vm.hostname = "preciseicinga2nrpeclient.local"
    preciseicinga2nrpeclient_config.hostmanager.enabled = true
    preciseicinga2nrpeclient_config.vm.network :private_network, ip: "10.0.1.95"
    #set some machine-specific options	
    preciseicinga2nrpeclient_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    preciseicinga2nrpeclient_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #A CentOS 6 Icinga 2 client
  config.vm.define "centos6icinga2nrpeclient".to_sym do |centos6icinga2nrpeclient_config|
    centos6icinga2nrpeclient_config.vm.box = "centos-6.6-amd64"
    centos6icinga2nrpeclient_config.vm.hostname = "centos6icinga2nrpeclient.local"
    centos6icinga2nrpeclient_config.hostmanager.enabled = true
    centos6icinga2nrpeclient_config.vm.network :private_network, ip: "10.0.1.96"
    centos6icinga2nrpeclient_config.vm.provider "virtualbox" do |v| 	
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    centos6icinga2nrpeclient_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #A CentOS 7 Icinga 2 client
  config.vm.define "centos7icinga2nrpeclient".to_sym do |centos7icinga2nrpeclient_config|
    centos7icinga2nrpeclient_config.vm.box = "centos-7.0-amd64"
    centos7icinga2nrpeclient_config.vm.hostname = "centos7icinga2nrpeclient.local"
    centos7icinga2nrpeclient_config.hostmanager.enabled = true
    centos7icinga2nrpeclient_config.vm.network :private_network, ip: "10.0.1.97"
    centos7icinga2nrpeclient_config.vm.provider "virtualbox" do |v| 	
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    centos7icinga2nrpeclient_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #A Debian 7 Icinga 2 client
  config.vm.define "debian7icinga2nrpeclient".to_sym do |debian7icinga2nrpeclient_config|
    debian7icinga2nrpeclient_config.vm.box = "debian-7.8-amd64"
    debian7icinga2nrpeclient_config.vm.hostname = "debian7icinga2nrpeclient.local"
    debian7icinga2nrpeclient_config.hostmanager.enabled = true
    debian7icinga2nrpeclient_config.vm.network :private_network, ip: "10.0.1.100"
    debian7icinga2nrpeclient_config.vm.provider "virtualbox" do |v| 	
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    debian7icinga2nrpeclient_config.vm.provision :shell, :path => "../provisioning_scripts/debian_puppet_agent.sh"
  end

  #Mail server VM for Icinga 2 to use as a relay
  config.vm.define "icinga2mail".to_sym do |icinga2mail_config|
    icinga2mail_config.vm.box = "ubuntu-14.04-server-amd64"
    icinga2mail_config.vm.hostname = "icinga2mail.local"
    icinga2mail_config.hostmanager.enabled = true
    icinga2mail_config.hostmanager.aliases = %w(icinga2mail)
    icinga2mail_config.vm.network :private_network, ip: "10.0.1.101"
    #set some machine-specific options	
    icinga2mail_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    icinga2mail_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #Mail server to hold user mail accounts that Icinga 2 will send emails to
  config.vm.define "usermail".to_sym do |usermail_config|
    usermail_config.vm.box = "ubuntu-14.04-server-amd64"
    usermail_config.vm.hostname = "usermail.local"
    usermail_config.hostmanager.enabled = true
    usermail_config.hostmanager.aliases = %w(usermail)
    usermail_config.vm.network :private_network, ip: "10.0.1.102"
    #set some machine-specific options	
    usermail_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    usermail_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #Logstash/Elasitcsearch/Kibana VM for looking at logs that the Icinga machines generate:
  config.vm.define "icinga2logging".to_sym do |icinga2logging_config|
    icinga2logging_config.vm.box = "ubuntu-14.04-server-amd64"
    icinga2logging_config.vm.hostname = "icinga2logging.local"
    icinga2logging_config.hostmanager.enabled = true
    icinga2logging_config.hostmanager.aliases = %w(icinga2logging kibana.icinga2logging.local)
    icinga2logging_config.vm.network :private_network, ip: "10.0.1.103"
    #set some machine-specific options	
    icinga2logging_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.cpus = 2
    end
    #Puppet agent provisioning script
    icinga2logging_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #Riemann/InfluxDB/Grafana VM for looking at metrics that the Icinga machines generate:
  config.vm.define "icinga2metrics".to_sym do |icinga2metrics_config|
    icinga2metrics_config.vm.box = "ubuntu-14.04-server-amd64"
    icinga2metrics_config.vm.hostname = "icinga2metrics.local"
    icinga2metrics_config.hostmanager.enabled = true
    icinga2metrics_config.hostmanager.aliases = %w(icinga2metrics icinga2metrics.local)
    icinga2metrics_config.vm.network :private_network, ip: "10.0.1.104"
    #set some machine-specific options	
    icinga2metrics_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.cpus = 2
    end
    #Puppet agent provisioning script
    icinga2metrics_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end
end