Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing for Puppet modules and manifests
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #Puppet master and PuppetDB server
  config.vm.define "icinga2master".to_sym do |icinga2master_config|
    icinga2master_config.vm.box = "ubuntu-14.04-server-amd64"
    icinga2master_config.vm.hostname = "icinga2master.local"
    icinga2master_config.hostmanager.enabled = true
    icinga2master_config.hostmanager.aliases = %w(puppetboard.icinga2master.local icinga2master puppet master)
    icinga2master_config.vm.network :private_network, ip: "10.0.1.80"
    #set some machine-specific options	
    icinga2master_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    icinga2master_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    icinga2master_config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    icinga2master_config.vm.synced_folder "hieradata/", "/etc/puppet/environments/production/hieradata", :nfs => true
    #Puppet icinga2master provisioning script
    icinga2master_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"
  end  

  #An Ubuntu 14.04 Icinga 2 server
  config.vm.define "trustyicinga2".to_sym do |trustyicinga2_config|
    trustyicinga2_config.vm.box = "ubuntu-14.04-server-amd64"
    trustyicinga2_config.vm.hostname = "trustyicinga2.local"
    trustyicinga2_config.hostmanager.enabled = true
    trustyicinga2_config.hostmanager.aliases = %w(trustyicinga2)
    trustyicinga2_config.vm.network :private_network, ip: "10.0.1.81"
    #set some machine-specific options	
    trustyicinga2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    trustyicinga2_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #An Ubuntu 12.04 Icinga 2 server
  config.vm.define "preciseicinga2".to_sym do |preciseicinga2_config|
    preciseicinga2_config.vm.box = "ubuntu-12.04-server-amd64"
    preciseicinga2_config.vm.hostname = "preciseicinga2.local"
    preciseicinga2_config.hostmanager.enabled = true
    preciseicinga2_config.hostmanager.aliases = %w(preciseicinga2)
    preciseicinga2_config.vm.network :private_network, ip: "10.0.1.82"
    #set some machine-specific options	
    preciseicinga2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    preciseicinga2_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #A CentOS 6 Icinga 2 server
  config.vm.define "centos6icinga2".to_sym do |centos6icinga2_config|
    centos6icinga2_config.vm.box = "centos-6.5-amd64"
    centos6icinga2_config.vm.hostname = "centos6icinga2.local"
    centos6icinga2_config.hostmanager.enabled = true
    centos6icinga2_config.hostmanager.aliases = %w(centos6icinga2)
    centos6icinga2_config.vm.network :private_network, ip: "10.0.1.83"
    #set some machine-specific options	
    centos6icinga2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    centos6icinga2_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #A CentOS 7 Icinga 2 server
  config.vm.define "centos7icinga2".to_sym do |centos7icinga2_config|
    centos7icinga2_config.vm.box = "centos-6.5-amd64"
    centos7icinga2_config.vm.hostname = "centos7icinga2.local"
    centos7icinga2_config.hostmanager.enabled = true
    centos7icinga2_config.hostmanager.aliases = %w(centos7icinga2)
    centos7icinga2_config.vm.network :private_network, ip: "10.0.1.84"
    #set some machine-specific options	
    centos7icinga2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    centos7icinga2_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #An Ubuntu 14.04 Icinga 2 client
  config.vm.define "trustyicinga2client".to_sym do |trustyicinga2client_config|
    trustyicinga2client_config.vm.box = "ubuntu-14.04-server-amd64"
    trustyicinga2client_config.vm.hostname = "trustyicinga2client.local"
    trustyicinga2client_config.hostmanager.enabled = true
    trustyicinga2client_config.vm.network :private_network, ip: "10.0.1.81"
    #set some machine-specific options	
    trustyicinga2client_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    trustyicinga2client_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #An Ubuntu 12.04 Icinga 2 client
  config.vm.define "preciseicinga2client".to_sym do |preciseicinga2client_config|
    preciseicinga2client_config.vm.box = "ubuntu-12.04-server-amd64"
    preciseicinga2client_config.vm.hostname = "preciseicinga2client.local"
    preciseicinga2client_config.hostmanager.enabled = true
    preciseicinga2client_config.vm.network :private_network, ip: "10.0.1.85"
    #set some machine-specific options	
    preciseicinga2client_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    preciseicinga2client_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #A CentOS 6 Icinga 2 client
  config.vm.define "centos6icinga2client".to_sym do |centos6icinga2client_config|
    centos6icinga2client_config.vm.box = "centos-6.5-amd64"
    centos6icinga2client_config.vm.hostname = "centos6icinga2client.local"
    centos6icinga2client_config.hostmanager.enabled = true
    centos6icinga2client_config.vm.network :private_network, ip: "10.0.1.86"
    centos6icinga2client_config.vm.provider "virtualbox" do |v| 	
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    centos6icinga2client_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #A CentOS 7 Icinga 2 client
  config.vm.define "centos7icinga2client".to_sym do |centos7icinga2client_config|
    centos7icinga2client_config.vm.box = "centos-7.0-amd64"
    centos7icinga2client_config.vm.hostname = "centos7icinga2client.local"
    centos7icinga2client_config.hostmanager.enabled = true
    centos7icinga2client_config.vm.network :private_network, ip: "10.0.1.87"
    centos7icinga2client_config.vm.provider "virtualbox" do |v| 	
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    centos7icinga2client_config.vm.provision :shell, :path => "../provisioning_scripts/el7_puppet_agent.sh"
  end

  #Mail server VM for Icinga 2 to use as a relay
  config.vm.define "icinga2mail".to_sym do |icinga2mail_config|
    icinga2mail_config.vm.box = "ubuntu-14.04-server-amd64"
    icinga2mail_config.vm.hostname = "icinga2mail.local"
    icinga2mail_config.hostmanager.enabled = true
    icinga2mail_config.hostmanager.aliases = %w(icinga2mail)
    icinga2mail_config.vm.network :private_network, ip: "10.0.1.88"
    #set some machine-specific options	
    icinga2mail_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    icinga2mail_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #Mail server to hold user mail accounts that Icinga 2 will send emails to
  config.vm.define "usermail".to_sym do |usermail_config|
    usermail_config.vm.box = "ubuntu-14.04-server-amd64"
    usermail_config.vm.hostname = "usermail.local"
    usermail_config.hostmanager.enabled = true
    usermail_config.hostmanager.aliases = %w(usermail)
    usermail_config.vm.network :private_network, ip: "10.0.1.89"
    #set some machine-specific options	
    usermail_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "256"]
    end
    #Puppet agent provisioning script
    usermail_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end
end
