Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing for Puppet modules and manifests
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  ####################
  ####################

  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #Puppet master and PuppetDB server
  config.vm.define "icinga2master".to_sym do |icinga2master_config|
    icinga2master_config.vm.box = "ubuntu-14.04-server-amd64"
    icinga2master_config.vm.hostname = "icinga2master.local"
    icinga2master_config.hostmanager.enabled = true
    icinga2master_config.hostmanager.aliases = %w(puppetboard.icinga2master.local icinga2master puppet master)
    icinga2master_config.vm.network :private_network, ip: "10.0.1.78"
    #set some machine-specific options	
    icinga2master_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    config.vm.synced_folder "hieradata/", "/etc/puppet/environments/production/hieradata", :nfs => true
    #Puppet icinga2master provisioning script
    icinga2master_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_master.sh"
  end  

  #trustyicinga2 server
  config.vm.define "trustyicinga2".to_sym do |trustyicinga2_config|
    trustyicinga2_config.vm.box = "ubuntu-14.04-server-amd64"
    trustyicinga2_config.vm.hostname = "trustyicinga2.local"
    trustyicinga2_config.hostmanager.enabled = true
    trustyicinga2_config.hostmanager.aliases = %w(trustyicinga2)
    trustyicinga2_config.vm.network :private_network, ip: "10.0.1.79"
    #set some machine-specific options	
    trustyicinga2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    trustyicinga2_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #Ubuntu Precise Icinga2 server
  config.vm.define "preciseicinga2".to_sym do |preciseicinga2_config|
    preciseicinga2_config.vm.box = "ubuntu-12.04-server-amd64"
    preciseicinga2_config.vm.hostname = "preciseicinga2.local"
    preciseicinga2_config.hostmanager.enabled = true
    preciseicinga2_config.hostmanager.aliases = %w(preciseicinga2)
    preciseicinga2_config.vm.network :private_network, ip: "10.0.1.85"
    #set some machine-specific options	
    preciseicinga2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    preciseicinga2_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #centosicinga2 server
  config.vm.define "centosicinga2".to_sym do |centosicinga2_config|
    centosicinga2_config.vm.box = "centos-6.5-amd64"
    centosicinga2_config.vm.hostname = "centosicinga2.local"
    centosicinga2_config.hostmanager.enabled = true
    centosicinga2_config.hostmanager.aliases = %w(centosicinga2)
    centosicinga2_config.vm.network :private_network, ip: "10.0.1.80"
    #set some machine-specific options	
    centosicinga2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    centosicinga2_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #an icinga2server client
  config.vm.define "icinga2client1".to_sym do |icinga2client1_config|
    icinga2client1_config.vm.box = "ubuntu-14.04-server-amd64"
    icinga2client1_config.vm.hostname = "icinga2client1.local"
    icinga2client1_config.hostmanager.enabled = true
    icinga2client1_config.vm.network :private_network, ip: "10.0.1.81"
    #set some machine-specific options	
    icinga2client1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    icinga2client1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #an icinga2server client
  config.vm.define "icinga2client2".to_sym do |icinga2client2_config|
    icinga2client2_config.vm.box = "centos-6.5-amd64"
    icinga2client2_config.vm.hostname = "icinga2client2.local"
    icinga2client2_config.hostmanager.enabled = true
    icinga2client2_config.vm.network :private_network, ip: "10.0.1.82"
    icinga2client2_config.vm.provider "virtualbox" do |v| 	
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    icinga2client2_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

  #an icinga2server client
  config.vm.define "icinga2client3".to_sym do |icinga2client1_config|
    icinga2client1_config.vm.box = "ubuntu-14.04-server-amd64"
    icinga2client1_config.vm.hostname = "icinga2client3.local"
    icinga2client1_config.hostmanager.enabled = true
    icinga2client1_config.vm.network :private_network, ip: "10.0.1.83"
    #set some machine-specific options	
    icinga2client1_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    icinga2client1_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_puppet_agent.sh"
  end

  #an icinga2server client
  config.vm.define "icinga2client4".to_sym do |icinga2client2_config|
    icinga2client2_config.vm.box = "centos-6.5-amd64"
    icinga2client2_config.vm.hostname = "icinga2client4.local"
    icinga2client2_config.hostmanager.enabled = true
    icinga2client2_config.vm.network :private_network, ip: "10.0.1.84"
    icinga2client2_config.vm.provider "virtualbox" do |v| 	
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
    icinga2client2_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end
end
