Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing for Puppet modules and manifests
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  config.vm.box = "centos-6.4-amd64"
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  
#Puppet master and PuppetDB server
config.vm.define "master".to_sym do |master_config|
	master_config.vm.box = "ubuntu-13.04-server-amd64"
	master_config.vm.hostname = "master.local"
	master_config.hostmanager.enabled = true
	master_config.hostmanager.aliases = %w(master puppet)
	master_config.vm.network :private_network, ip: "10.0.1.79"
	#set some machine-specific options	
	master_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules" #:nfs => true
    config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/manifests", "/etc/puppet/manifests" #:nfs => true
    #Puppet master provisioning script
    master_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1304_puppet_master_script.sh"
end  
  
 #Icinga server
config.vm.define "icinga".to_sym do |icinga_config|
	icinga_config.vm.box = "ubuntu-13.04-server-amd64"
	icinga_config.vm.hostname = "icinga.local"
	icinga_config.hostmanager.enabled = true
	icinga_config.hostmanager.aliases = %w(icinga)
	icinga_config.vm.network :private_network, ip: "10.0.1.80"
	#set some machine-specific options	
	icinga_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #Puppet agent provisioning script
	icinga_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1304_puppet_agent_script.sh"
end

#an icinga client
config.vm.define "client1".to_sym do |client1_config|
	client1_config.vm.box = "centos-6.4-amd64"
	client1_config.vm.hostname = "client1.local"
	client1_config.hostmanager.enabled = true
	client1_config.vm.network :private_network, ip: "10.0.1.81"
	#set some machine-specific options	
	client1_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
	end
	#Puppet agent provisioning script
	client1_config.vm.provision :shell, :path => "../provisioning_scripts/rhel_centos_puppet_agent_script.sh"
end

 #an icinga client
config.vm.define "client2".to_sym do |client2_config|
	client2_config.vm.box = "ubuntu-13.04-server-amd64"
	client2_config.vm.hostname = "client2.local"
	client2_config.hostmanager.enabled = true
	client2_config.vm.network :private_network, ip: "10.0.1.82"
    client2_config.vm.provider "virtualbox" do |v| 	
    	#change the amount of RAM 
    	v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	client2_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1304_puppet_agent_script.sh"
end

#a mail server for Icinga to send notifications to
config.vm.define "mail".to_sym do |mail_config|
	mail_config.vm.box = "ubuntu-13.04-server-amd64"
	mail_config.vm.hostname = "mail.local"
	mail_config.hostmanager.enabled = true
	mail_config.vm.network :private_network, ip: "10.0.1.84"
	#set some machine-specific options	
	mail_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	mail_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_1304_puppet_agent_script.sh"
end

end