Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ####################
  # Snippets to use
  ####################

  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true

  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules"
  config.vm.synced_folder "manifests/", "/etc/puppet/manifests"
  config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/hieradata", "/etc/puppet/hieradata"

  ####################
  ####################
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  #incorporate offline box's IPs into the /etc/hosts of boxes that are up/being brought up
  config.hostmanager.include_offline = true

  #Groovy Puppet master
  config.vm.define "groovymaster".to_sym do |groovymaster_config|
    groovymaster_config.vm.box = "ubuntu-13.10-server-amd64"
    groovymaster_config.vm.hostname = "groovymaster.local"
    groovymaster_config.hostmanager.enabled = true
    groovymaster_config.hostmanager.aliases = %w(groovymaster.local groovymaster puppet puppet.local groovypuppetboard.puppet.local groovypuppetdb.puppet.local)
    groovymaster_config.vm.network :private_network, ip: "10.0.1.54"
    #set some machine-specific options	
    groovymaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    groovymaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master_script.sh"
  end

  #Ubuntu Groovy VM
  config.vm.define "ubuntugroovy".to_sym do |ubuntugroovy_config|
    ubuntugroovy_config.vm.box = "centos-6.5-amd64"
    ubuntugroovy_config.vm.hostname = "ubuntugroovy.local"
    ubuntugroovy_config.hostmanager.enabled = true
    ubuntugroovy_config.vm.network :private_network, ip: "10.0.1.55"
    #set some machine-specific options	
    ubuntugroovy_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    ubuntugroovy_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end

  #CentOS Groovy VM
  config.vm.define "centosgroovy".to_sym do |centosgroovy_config|
    centosgroovy_config.vm.box = "centos-6.5-amd64"
    centosgroovy_config.vm.hostname = "centosgroovy.local"
    centosgroovy_config.hostmanager.enabled = true
    centosgroovy_config.vm.network :private_network, ip: "10.0.1.56"
    #set some machine-specific options	
    centosgroovy_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    centosgroovy_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end
end
