Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #Puppet master and denyhosts server
  config.vm.define "denymaster".to_sym do |master_config|
    master_config.vm.box = "ubuntu-13.10-server-amd64"
    master_config.vm.hostname = "denymaster.local"
    master_config.hostmanager.aliases = %w(master puppet master.local puppetboard.denymaster.local)
    master_config.vm.network :private_network, ip: "10.0.1.70"
    #set some machine-specific options	
    master_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/environments/production/modules", :nfs => true
    config.vm.synced_folder "manifests/", "/etc/puppet/environments/production/manifests", :nfs => true
    config.vm.synced_folder "hieradata", "/etc/puppet/hieradata", :nfs => true
    #Puppet master provisioning script
    
    master_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master.sh"
  end

  #an SSH client
  config.vm.define "denyclient1".to_sym do |client1_config|
    client1_config.vm.box = "centos-6.5-amd64"
    client1_config.vm.hostname = "denyclient1.local"
    client1_config.vm.network :private_network, ip: "10.0.1.71"
    #set some machine-specific options	
    client1_config.vm.provider "virtualbox" do |v|
         #change the amount of RAM 
          v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  client1_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
  end

   #an SSH client
  config.vm.define "denyclient2".to_sym do |client2_config|
    client2_config.vm.box = "ubuntu-13.10-server-amd64"
    client2_config.vm.hostname = "denyclient2.local"
    client2_config.vm.network :private_network, ip: "10.0.1.72"
    #set some machine-specific options	
    client2_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  client2_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end

#   #a mail server
#   config.vm.define "denymail".to_sym do |denymail_config|
#     denymail_config.vm.box = "centos-6.5-amd64"
#     denymail_config.vm.hostname = "denymail.local"
#     denymail_config.vm.network :private_network, ip: "10.0.1.73"
#     #set some machine-specific options	
#     denymail_config.vm.provider "virtualbox" do |v|
#         #change the amount of RAM 
#         v.customize ["modifyvm", :id, "--memory", "512"]
#       end
#   #Puppet agent provisioning script
# 	denymail_config.vm.provision :shell, :path => "../provisioning_scripts/el6_puppet_agent.sh"
#   end
end
