Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #Puppet master
  config.vm.define "newmetricmaster".to_sym do |newmetricmaster_config|
    newmetricmaster_config.vm.box = "ubuntu-13.10-server-amd64"
    newmetricmaster_config.vm.hostname = "newmetricmaster.local"
    newmetricmaster_config.hostmanager.aliases = %w(master puppet master.local puppetboard.newmetricmaster.local)
    newmetricmaster_config.vm.network :private_network, ip: "10.0.1.70"
    #set some machine-specific options	
    newmetricmaster_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    #NFS folder sharing for Puppet modules and manifests
    newmetricmaster_config.vm.synced_folder "/Users/nick/Documents/git/puppet-code/modules", "/etc/puppet/modules", :nfs => true
    newmetricmaster_config.vm.synced_folder "manifests/", "/etc/puppet/manifests", :nfs => true
    newmetricmaster_config.vm.synced_folder "hieradata", "/etc/puppet/hieradata", :nfs => true
    #Puppet master provisioning script
    newmetricmaster_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_master.sh"
  end
  
  #A machine running InfluxDB
  config.vm.define "influxdb".to_sym do |influxdb_config|
    influxdb_config.vm.box = "ubuntu-13.10-server-amd64"
    influxdb_config.vm.hostname = "influxdb.local"
    influxdb_config.vm.network :private_network, ip: "10.0.1.71"
    #set some machine-specific options	
    influxdb_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    #Puppet agent provisioning script
	  influxdb_config.vm.provision :shell, :path => "../provisioning_scripts/ubuntu_saucy_puppet_agent.sh"
  end

end
