Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  ####################
  # Snippets to use
  ####################
  
  #NFS folder sharing
  #config.vm.synced_folder "modules", "/etc/puppet/modules", :nfs => true
  
  ####################
  ####################
  config.vm.box = "centos-6.4-amd64"
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  
 #Icinga server
config.vm.define "sshserver".to_sym do |icinga_config|
	icinga_config.vm.box = "centos-6.4-amd64"
	icinga_config.vm.hostname = "sshserver.local"
	icinga_config.hostmanager.enabled = true
	icinga_config.vm.network :private_network, ip: "10.0.1.70"
	#set some machine-specific options	
	icinga_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "1024"]
    end
end

#an SSH client
config.vm.define "client1".to_sym do |client1_config|
	client1_config.vm.box = "centos-6.4-amd64"
	client1_config.vm.hostname = "sshclient1.local"
	client1_config.hostmanager.enabled = true
	client1_config.vm.network :private_network, ip: "10.0.1.71"
	#set some machine-specific options	
	client1_config.vm.provider "virtualbox" do |v|
       #change the amount of RAM 
        v.customize ["modifyvm", :id, "--memory", "512"]
	end
end

 #an SSH client
config.vm.define "client2".to_sym do |client2_config|
	client2_config.vm.box = "centos-6.4-amd64"
	client2_config.vm.hostname = "sshclient2.local"
	client2_config.hostmanager.enabled = true
	client2_config.vm.network :private_network, ip: "10.0.1.72"
	#set some machine-specific options	
	client2_config.vm.provider "virtualbox" do |v|
    	#change the amount of RAM 
    	v.customize ["modifyvm", :id, "--memory", "512"]
    end
end

#a mail server
config.vm.define "denymail".to_sym do |denymail_config|
	denymail_config.vm.box = "centos-6.4-amd64"
	denymail_config.vm.hostname = "denymail.local"
	denymail_config.hostmanager.enabled = true
	denymail_config.vm.network :private_network, ip: "10.0.1.73"
	#set some machine-specific options	
	denymail_config.vm.provider "virtualbox" do |v|
    	#change the amount of RAM 
    	v.customize ["modifyvm", :id, "--memory", "512"]
    end
end
end