Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  #vagrant-hostmanager plugin options
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  #update the /etc/hosts of the host OS
  config.hostmanager.manage_host = true
  
  #An Ubuntu 14.04 Trusty Puppet master machine
  config.vm.define "centos7".to_sym do |centos7_config|
    centos7_config.vm.box = "centos-7.1-amd64"
    centos7_config.vm.hostname = "centos7.local"
    centos7_config.vm.network :private_network, ip: "10.0.1.70"
    #set some machine-specific options	
    centos7_config.vm.provider "virtualbox" do |v|
      #change the amount of RAM 
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.gui = false
    end
  end
end
